#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ${SRC_MESONH}/src/LIB/Python/* .
ln -sf ../002_mesonh/ARM__.1.CEN4T.000.nc .

python3 plot_005_ARM.py
${POSTRUN} display tempgraph1.png
${POSTRUN} display tempgraph2.png
${POSTRUN} display tempgraph3.png
${POSTRUN} display tempgraph4.png
#${POSTRUN} convert *.png 005_ARM.pdf
#${POSTRUN} evince 005_ARM.pdf
