#!/bin/sh
#SBATCH -J RECYL_1
#SBATCH -N 1            # nodes number
#SBATCH -n 40            # CPUs number (on all nodes) 
#SBATCH -o ideal.eo%j   #
#SBATCH -e ideal.eo%j   #
#SBATCH -t 00:05:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-IBM

export MPIRUN="Mpirun -np 40"

set -x
set -e

time ${MPIRUN} PREP_IDEAL_CASE${XYZ}
cd ../002_mesonh
sbatch run_mesonh
