all:
	cd 001_pgd1    && run_prep_pgd
	cd 002_pgd2    && run_prep_pgd
	cd 003_prep_nest_pgd && run_prep_nest
	cd 004_prep_real_d1 && run_prep_real_case
	cd 005_spawning  && run_spawning
	cd 006_prep_real_d2 && run_prep_real_case
	cd 007_run  && run_mesonh
