#!/bin/sh
set -x
set -e
rm -f 16JAN* OUT*  
#
# First modele
#
ln -sf  ../008_run2/16JAN.1.12B18.001.*??? .
ln -sf ../003_nest/16JAN98_9km.neste1.* .
ln -sf ../003_nest/16JAN98_36km.neste1.* .

cp  DIAG1.nam1 DIAG1.nam
time ${MPIRUN} DIAG${XYZ}
#
# 2nd modele
#
ln -sf  ../008_run2/16JAN.2.12B18.001.*??? .
cp  DIAG1.nam2 DIAG1.nam
time ${MPIRUN} DIAG${XYZ}
