#!/bin/sh
#SBATCH -J run_armles
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 8            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run_armles.eo%j   #
#SBATCH -e run_armles.eo%j   #
#SBATCH -t 02:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname
ln -sf ../../001_prep_ideal_case/KW78* .

. /home/cnrm_other/ge/mrmh/rodierq/MNH-56-base-Christelle/MNH-56-base-Christelle/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-1-MPIAUTO-DEBUG
export MPIRUN="Mpirun -np 8"

time ${MPIRUN} MESONH${XYZ}

