#!/bin/sh
#SBATCH -J RECYL_3
#SBATCH -N 1            # nodes number
#SBATCH -n 10            # CPUs number (on all nodes) 
#SBATCH -o ideal.eo%j   #
#SBATCH -e ideal.eo%j   #
#SBATCH -t 01:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-IBM
ln -sf ../002_mesonh/MUSTFATHER_PGD.des RE1_PGD.des
ln -sf ../002_mesonh/MUSTFATHER_PGD.nc RE1_PGD.nc
ln -sf ../002_mesonh/RE1_200ks.nc RE1.nc
ln -sf ../002_mesonh/RE1_200ks.des RE1.des

export MPIRUN="Mpirun -np 10"

set -x
set -e

time ${MPIRUN} SPAWNING${XYZ}
sed 's/RE1/RE1.spa00/' RE1.spa00.des > RE1.spa00.des2
mv -f RE1.spa00.des2 RE1.spa00.des

sed "s/CINIFILEPGD     = \" /CINIFILEPGD     = \"RE1.spa00/" RE1.spa00.des > temp
mv -f temp RE1.spa00.des

cd ../004_prep_real_D2
sbatch run_prep
