all:
	cd 001_prep_ideal && run_prep_ideal_case_xyz
	cd 002_mesonh      && run_mesonh_xyz
	cd 003_python            && run_python

clean:
	cd 001_prep_ideal && clean_prep_ideal_case_xyz
	cd 002_mesonh      && clean_mesonh_xyz
	cd 003_python            && clean_python
