#!/bin/sh
#SBATCH -J supercell    
#SBATCH -N 1         # nodes number
#SBATCH -n 128         # CPUs number (on all nodes) 
#SBATCH -o ideal.eo%j   #
#SBATCH -e ideal.eo%j   #
#SBATCH -t 00:05:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
#set -e
# Nom de la machine
hostname

export MPIRUN="Mpirun -np 128"

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-SUPERCELL

time ${MPIRUN} PREP_IDEAL_CASE${XYZ}

# ménage du repertoire
rm -f file_for_xtransfer pipe_name
cd ..
sbatch run_all_mesonh
