#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ${SRC_MESONH}/src/LIB/Python/* .
ln -sf ../003_diag/KWRAI.1.SEGCH.004*.nc .

python3 plot_011_KW78CHEM.py
${POSTRUN} convert *.png 011_KW78CHEM.pdf
${POSTRUN} evince 011_KW78CHEM.pdf
