#!/bin/bash
#SBATCH -J ALM3_04
#SBATCH -N 2            # nodes number (=NBP)
#SBATCH -n 256            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal_fire.eo%j   #
#SBATCH -e ideal_fire.eo%j   #
#SBATCH -t 03:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 256"

set -x
set -e

ln -sf ../01_PREP/FIRE_* .
ln -sf ../02_SPAWN/FIRE_INI.spa* .
ln -sf ../03_RUN_PRE/FIRE_.1.SEG1.003* .
ln -sf ../03_RUN_PRE/FIRE_.2.SEG1.003* .

time ${MPIRUN} MESONH${XYZ}

rm -f file_for_xtransfer pipe_name REMAP*

sbatch run_python
