#!/bin/sh
#SBATCH -J prep_ifs
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 2            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_ifs.eo%j   #
#SBATCH -e prep_ifs.eo%j   #
#SBATCH -t 00:30:00    # time limit
# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

export MPIRUN="Mpirun -np 2"

ln -sf ../PGD/PGD_FRANCE* .
ln -sf /home/cnrm_other/ge/mrmh/rodierq/SAVE/GRIB_KTEST/ecmwf.EA.20180513.00_hpa .
set -x
set -e
 
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

time ${MPIRUN} PREP_REAL_CASE${XYZ}
sbatch run_python
