#!/bin/sh
#SBATCH -J azf_pgd
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 4            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 00:30:00    # time limit
#
## Echo des commandes
ulimit -c 0
ulimit -s unlimited
## Arrete du job des la premiere erreur
set -e
## Nom de la machine
hostname
#
#
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

#
export MPIRUN="Mpirun -np 4"
#
rm -f *ne.??? OUTPUT_LISTING* pipe* *.tex

ln -sf ../002_pgd2/PGD_AZF_500m.* .
ln -sf ../001_pgd1/PGD_AZF_2.5km.* .

set -x
set -e

time ${MPIRUN} PREP_NEST_PGD${XYZ}
cd ../004_arp2lfi/
sbatch run_arp2lfi_xyz
