#!/bin/sh
#SBATCH -J salt_prep
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 24           # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 00:45:00    # time limit
#
## Echo des commandes
ulimit -c 0
ulimit -s unlimited
## Arrete du job des la premiere erreur
set -e
## Nom de la machine
#hostname
#
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 24"

set -x
set -e

ln -sf ~rodierq/SAVE/GRIB_KTEST/ecmwf.OD.20180118* .
ln -sf ../002_prep_nest/Arome* .
ln -sf ../001_prep_pgd/Arome* .

#Préparation de l'état initial
#Preparation du domaine père
cp -f PRE_REAL1.nam_dom1 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}

#Préparation des fichiers de couplage toutes les 6h (IFS)
cp -f PRE_REAL1.nam_dom1_cpl1 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}

cp -f PRE_REAL1.nam_dom1_cpl2 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}

cp -f PRE_REAL1.nam_dom1_cpl3 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}

sbatch run_prep_fils
