#!/bin/sh
#SBATCH -J salt_prep
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 4           # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 00:45:00    # time limit
#
## Echo des commandes
ulimit -c 0
ulimit -s unlimited
## Arrete du job des la premiere erreur
set -e
## Nom de la machine
#hostname
#
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 4"

set -x
set -e

#Préparation du domaine fils
time ${MPIRUN} SPAWNING${XYZ}

cp -f PRE_REAL1.nam_dom2 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}

cd ../004_run_mesonh
sbatch run_mesonh
