#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ${SRC_MESONH}/src/LIB/Python/*.py .

ln -sf ../002_mesonh/BUBBL.1.CEN4T.0*.nc .
python3 plot_COLD_BUBBLE.py
convert *.png COLD_BUBBLE1.pdf
# Le 3e trace n'est pas converti dans le PDF ????? Bypass:
convert tempgraph3.png COLD_BUBBLE2.pdf
pdfunite COLD_BUBBLE1.pdf COLD_BUBBLE2.pdf COLD_BUBBLE.pdf
rm -f COLD_BUBBLE1.pdf COLD_BUBBLE2.pdf
