#!/bin/sh
#SBATCH -J azf
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 00:30:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 1"

rm -f *spa04.* OUTPUT_LISTING* pipe* *.tex
ln -sf  ../003_nest/PGD_AZF_2.5km.nestne.* .
ln -sf  ../003_nest/PGD_AZF_500m.nestne.* .
ln -sf  ../004_arp2lfi/CPL_J1_20010921.09.* .

set -x
set -e

time ${MPIRUN} SPAWNING${XYZ}
cd ../006_preal/
sbatch run_preal_xyz
