#!/bin/bash
#SBATCH -J ADNR3_04
#SBATCH -N 2            # nodes number (=NBP)
#SBATCH -n 256            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal_fire.eo%j   #
#SBATCH -e ideal_fire.eo%j   #
#SBATCH -t 05:10:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2
export MPIRUN="Mpirun -np 256"

set -x
set -e

ln -sf ../01_PREP/DAD_PGD* .
ln -sf ../02_RUN_PERE/DADDY.1.SEG1.003.* .
ln -sf ../03_SPAWN/SON* .

time ${MPIRUN} MESONH${XYZ}

rm -f file_for_xtransfer pipe_name

cd ../05_RUN_EOL/
sbatch run_mesonh
