#!/bin/sh
#SBATCH -J azf_pgd
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 4            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 00:30:00    # time limit
#
## Echo des commandes
ulimit -c 0
ulimit -s unlimited
## Arrete du job des la premiere erreur
set -e
## Nom de la machine
hostname
#
#
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

#
export MPIRUN="Mpirun -np 4"
#

ln -sf $MESONH/PGD/ECOCLIMAP_v2.0.* .
ln -sf $MESONH/PGD/gtopo* .
ln -sf $MESONH/PGD/clay* .
ln -sf $MESONH/PGD/sand* .

set -x
set -e

time ${MPIRUN} PREP_PGD${XYZ}

rm -f *.dir *.hdr
cd ../002_pgd2
sbatch run_prep_pgd_xyz
