#!/bin/sh
#SBATCH -J RECYC_2
#SBATCH -N 10            # nodes number
#SBATCH -n 1024            # CPUs number (on all nodes) 
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 08:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 
ln -sf ../001_prep_ideal_case/MUSTFATHER* .
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-IBM

export MPIRUN="Mpirun -np 1024"

set -x
set -e

time ${MPIRUN} MESONH${XYZ}
mv MNHOU.1.SEGM.004.des RE1_200ks.des
mv MNHOU.1.SEGM.004.nc RE1_200ks.nc
ln -sf RE1_200ks.nc RE1.nc
ln -sf RE1_200ks.des RE1.des
cd ../003_spawn_D2/
sbatch run_spawning
