#!/bin/sh
#SBATCH -J IHOP1D
#SBATCH -N 1           # nodes number
#SBATCH -n 1         # CPUs number (on all nodes) 
#SBATCH -o G1_.eo%j   #
#SBATCH -e G1_.eo%j   #
#SBATCH -t 00:30:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-GABLS1

export MPIRUN="Mpirun -np 1 "

set -x
set -e

rm -f RBL89* RRM17* OUTPUT_LISTING* pipe_name*

cp -f EXSEG1.nam_BL89 EXSEG1.nam
time ${MPIRUN} MESONH${XYZ}

cp -f EXSEG1.nam_RM17 EXSEG1.nam
time ${MPIRUN} MESONH${XYZ}
