#!/bin/bash 

ncl plot_coupling_model_toy.ncl
#python plot_coupling_model_toy.py

${POSTRUN} display */*0.png
${POSTRUN} display */*1.png
${POSTRUN} display */*2.png
${POSTRUN} display */*3.png
${POSTRUN} display */*4.png

