#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x

ln -sf ../003_mesonh/REUNI.1.00A20.004.nc .

rm -f visu_Reunion.*.png

ncl plot_Reunion.ncl
${POSTRUN} display visu_Reunion.000001.png
${POSTRUN} display visu_Reunion.000002.png
${POSTRUN} display visu_Reunion.000003.png
${POSTRUN} display visu_Reunion.000004.png
${POSTRUN} display visu_Reunion.000005.png
${POSTRUN} display visu_Reunion.000006.png
${POSTRUN} display visu_Reunion.000007.png
exit 0
