#!/bin/sh
#SBATCH -J prep_fog
#SBATCH -N 20            # nodes number (=NBP)
#SBATCH -n 200            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_fog.eo%j   #
#SBATCH -e prep_fog.eo%j   #
#SBATCH -t 04:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 200"

set -x
set -e

ln -sf $HOME/SAVE/GRIB_KTEST/arome.AN.2009022* .

ls -lrt

for DATE in '20090227.18' '20090227.21' '20090228.00' '20090228.03' '20090228.06'
do   
rm -f CPL_${DATE}.???
cp PRE_REAL1.nam_${DATE} PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep.${DATE}
 
ls -lrt

done


rm -f  PRE_REAL1.nam
rm -f arome*
rm -f file_for_xtransfer pipe_name


ls -lrt

sbatch run_mesonh1
ja
