#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ${SRC_MESONH}/src/LIB/Python/* .
ln -sf ../004_diag/REUNI.1.00A20.004*.nc .

python3 plot_004_Reunion.py
${POSTRUN} display tempgraph1.png
${POSTRUN} display tempgraph2.png
#${POSTRUN} convert *.png 004_Reunion.pdf
#${POSTRUN} evince 004_Reunion.pdf
