all:
	cd 001_prep_ideal_case && run_prep_ideal_case_xyz
	cd 002_mesonh          && run_mesonh_xyz
	cd 003_python          && run_python
	cd 004_ncl             && run_ncl

clean:
	cd 001_prep_ideal_case && clean_prep_ideal_case_xyz
	cd 002_mesonh          && clean_mesonh_xyz
	cd 003_python          && clean_python
	cd 004_ncl             && clean_ncl
