#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ../004_pgd4/16JAN98_2250.{des,lfi,nc} .
ln -sf ../003_pgd3/16JAN98_4500.{des,lfi,nc} .
ln -sf ../002_pgd2/16JAN98_9km.{des,lfi,nc} .
ln -sf ../001_pgd1/16JAN98_36km.{des,lfi,nc} .
rm -f *e1.??? OUTPUT_LISTING* pipe* *.tex
time ${MONORUN} PREP_NEST_PGD${XYZ}
#ddd --directory=~/DEV/.../PREP_NEST_PGD
