all:
	cd 001_pgd3    			&& run_prep_pgd
	cd 002_pgd4    			&& run_prep_pgd
	cd 003_prep_nest_pgd          	&& run_prep_nest
	cd 004_spawning_d2tod3_INIT   	&& run_spawning
	cd 005_prep_real_d3_INIT      	&& run_prep_real_case
	cd 006_spawning_d2tod3_CPL1	&& run_spawning
	cd 007_prep_real_d3_CPL1 	&& run_prep_real_case
	cd 008_spawning_d4 		&& run_spawning
	cd 009_prep_real_d4 		&& run_prep_real_case
	cd 010_run	 		&& run_mesonh
