#!/bin/bash
#SBATCH -J post
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal_fire.eo%j   #
#SBATCH -e ideal_fire.eo%j   #
#SBATCH -t 03:00:00    # time limit

module load python/2.7.17

python eol_2D_fields.py DTU10.1.SEG1.003.nc UT
python eol_2D_fields.py DTU10.1.SEG1.003.nc UMME
python eol_aerodyn_var.py DTU10.1.SEG1.003.nc

convert *.png ADR_1WT_opti.pdf
