!MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
!MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!MNH_LIC for details. version 1.
#ifdef MNH_NCWRIT
MODULE MODD_PARAM
  IMPLICIT NONE 

  CHARACTER(LEN=*), PARAMETER :: VERSION_ID='OUTPUT FROM MESONH MODEL'
  INTEGER, PARAMETER :: INT2   = 1
  INTEGER, PARAMETER :: FLOAT2 = 2
  INTEGER, PARAMETER :: TEXT  = 3
  INTEGER, PARAMETER :: BOOL  = 4

  INTEGER, PARAMETER :: NOTFOUND = -1

  INTEGER, PARAMETER :: FM_FIELD_SIZE = 32
  
END MODULE MODD_PARAM
#endif
