MODULE MODD_NETCDF
IMPLICIT NONE 

INTEGER,PARAMETER :: IDCDF_KIND = SELECTED_INT_KIND(8)

TYPE IOCDF
   INTEGER(KIND=IDCDF_KIND) :: NCID
   TYPE(DIMCDF), POINTER :: DIMX
   TYPE(DIMCDF), POINTER :: DIMY
   TYPE(DIMCDF), POINTER :: DIMZ
   TYPE(DIMCDF), POINTER :: DIMSTR
   TYPE(DIMCDF), POINTER :: DIMLIST
END TYPE IOCDF

TYPE DIMCDF
   CHARACTER(LEN=8)         :: NAME
   INTEGER(KIND=IDCDF_KIND) :: LEN
   INTEGER(KIND=IDCDF_KIND) :: ID
   TYPE(DIMCDF), POINTER    :: NEXT
END TYPE DIMCDF

END MODULE MODD_NETCDF
