!MNH_LIC Copyright 2016 CNRS, Meteo-France and Universite Paul Sabatier
!MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
!MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!MNH_LIC for details. version 1.
MODULE MODE_FIELD
!
USE MODD_PARAMETERS
!
IMPLICIT NONE
!
INTEGER,PRIVATE,PARAMETER :: MAXFIELDS = 100
INTEGER,PARAMETER :: TYPEUNDEF = -1, TYPEINT = 1, TYPELOG = 2, TYPEREAL = 3, TYPECHAR = 4
!
TYPE TFIELDPTR_X2D
  REAL,DIMENSION(:,:),  POINTER :: DATA => NULL()
END TYPE TFIELDPTR_X2D
!
TYPE TFIELDPTR_X3D
  REAL,DIMENSION(:,:,:),POINTER :: DATA => NULL()
END TYPE TFIELDPTR_X3D
!
!Structure describing the characteristics of a field
TYPE TFIELDDATA
  CHARACTER(LEN=NMNHNAMELGTMAX) :: CMNHNAME  = '' !Name of the field (for MesoNH, non CF convention)
  CHARACTER(LEN=32)  :: CSTDNAME  = '' !Standard name (CF convention)
  CHARACTER(LEN=32)  :: CLONGNAME = '' !Long name (CF convention)
  CHARACTER(LEN=32)  :: CUNITS    = '' !Canonical units (CF convention)
  CHARACTER(LEN=2)   :: CDIR      = '' !Type of the data field (XX,XY,--...)
  CHARACTER(LEN=100) :: CCOMMENT  = '' !Comment (for MesoNH, non CF convention)
  INTEGER            :: NGRID     = -1 !Localization on the model grid
  INTEGER            :: NTYPE     = TYPEUNDEF !Datatype
  INTEGER            :: NDIMS     = 0  !Number of dimensions
  TYPE(TFIELDPTR_X2D),DIMENSION(:),ALLOCATABLE :: TFIELD_X2D !Pointer to the real 2D fields (one per nested mesh)
  TYPE(TFIELDPTR_X3D),DIMENSION(:),ALLOCATABLE :: TFIELD_X3D !Pointer to the real 3D fields (one per nested mesh)
END TYPE TFIELDDATA
!
LOGICAL,SAVE :: LFIELDLIST_ISINIT = .FALSE.
TYPE(TFIELDDATA),DIMENSION(MAXFIELDS),SAVE :: TFIELDLIST
!
CONTAINS
!
SUBROUTINE INI_FIELD_LIST(KMODEL)
!
USE MODD_CONF, ONLY: NMODEL
!
INTEGER,INTENT(IN),OPTIONAL :: KMODEL
!
INTEGER :: IDX, IMODEL
!
!F90/95: TFIELDLIST(1) = TFIELDDATA('UT','x_wind','m s-1','XY','X_Y_Z_U component of wind (m/s)',2)
!F2003:
!TFIELDLIST(1) = TFIELDDATA(CMNHNAME='UT',CSTDNAME='x_wind',CUNITS='m s-1',CDIR='XY',&
!                           CCOMMENT='X_Y_Z_U component of wind (m/s)',NGRID=2)
!
PRINT *,'PW: INI_FIELD_LIST called'
print *,'PW: nmodel=',nmodel
IF (LFIELDLIST_ISINIT) THEN
  PRINT *,'ERROR: INI_FIELD_LIST already called'
  RETURN
END IF
LFIELDLIST_ISINIT = .TRUE.
!
IF (PRESENT(KMODEL)) THEN
  IMODEL = KMODEL
ELSE
  IMODEL = NMODEL
END IF
!
IDX = 1
!
TFIELDLIST(IDX)%CMNHNAME   = 'MASDEV'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH version (without bugfix)'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'BUGFIX'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH bugfix number'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'BIBUSER'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: user binary library'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'PROGRAM'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH family: used program'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'FILETYPE'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: type of this file'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'MY_NAME'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: filename (no extension)'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'DAD_NAME'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: filename of the dad file'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'DXRATIO'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: DXRATIO'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Resolution ratio between this mesh and its father in x-direction'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'DYRATIO'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: DYRATIO'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Resolution ratio between this mesh and its father in y-direction'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'XOR'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: XOR'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Horizontal position of this mesh relative to its father'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'YOR'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: YOR'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Vertical position of this mesh relative to its father'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'UT'
TFIELDLIST(IDX)%CSTDNAME   = 'x_wind'
TFIELDLIST(IDX)%CLONGNAME  = ''
TFIELDLIST(IDX)%CUNITS     = 'm s-1'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_U component of wind (m/s)'
TFIELDLIST(IDX)%NGRID      = 2
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'VT'
TFIELDLIST(IDX)%CSTDNAME   = 'y_wind'
TFIELDLIST(IDX)%CLONGNAME  = ''
TFIELDLIST(IDX)%CUNITS     = 'm s-1'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_V component of wind (m/s)'
TFIELDLIST(IDX)%NGRID      = 3
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'WT'
TFIELDLIST(IDX)%CSTDNAME   = 'upward_air_velocity'
TFIELDLIST(IDX)%CLONGNAME  = ''
TFIELDLIST(IDX)%CUNITS     = 'm s-1'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_vertical wind (m/s)'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'THT'
TFIELDLIST(IDX)%CSTDNAME   = 'air_potential_temperature'
TFIELDLIST(IDX)%CLONGNAME  = ''
TFIELDLIST(IDX)%CUNITS     = 'K'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_potential temperature (K)'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
TFIELDLIST(IDX)%CMNHNAME   = 'ACPRR'
TFIELDLIST(IDX)%CSTDNAME   = 'rainfall_amount'
TFIELDLIST(IDX)%CLONGNAME  = ''
!PW: TODO: CF-convention prefers 'kg m-2'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_ACcumulated Precipitation Rain Rate (m)'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 2
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X2D(IMODEL))
IDX = IDX+1
!
PRINT *,'INFO: INI_FIELD_LIST: number of used fields=',IDX-1,' out of ',MAXFIELDS
!
#if 0
!
TFIELDLIST(IDX)%CMNHNAME   = ''
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = ''
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 
TFIELDLIST(IDX)%NTYPE      = 
TFIELDLIST(IDX)%NDIMS      = 
ALLOCATE(TFIELDLIST(IDX)%TFIELD_xxxD(IMODEL))
IDX = IDX+1
#endif

END SUBROUTINE INI_FIELD_LIST
!
SUBROUTINE FIND_FIELD_ID_FROM_MNHNAME(HMNHNAME,KID,KRESP)
!
CHARACTER(LEN=*),            INTENT(IN) :: HMNHNAME !Name of the field to find
INTEGER,                     INTENT(OUT):: KID      !Index of the field
INTEGER,                     INTENT(OUT):: KRESP    !Return-code 
!
INTEGER :: IDX,JI
INTEGER :: ICOUNT
INTEGER,SAVE :: IFIRSTGUESS=1 !Store first field to test
!
!PW: TODO: possible optimizations:
! * Classement alphanumerique + index vers 1er champ commencant par caractere
! * Classement dans l'ordre des ecritures + stockage dernier hit + reboucler depuis le debut => DONE
!
IF (.NOT.LFIELDLIST_ISINIT) THEN
  PRINT *,'FATAL: FIND_FIELD_ID_FROM_MNHNAME: TFIELDLIST not yet initialized'
  STOP
END IF
!
KID = 0
KRESP = 0
ICOUNT = 0
IDX = IFIRSTGUESS
!
DO
  ICOUNT = ICOUNT + 1
  IF (TRIM(TFIELDLIST(IDX)%CMNHNAME)=='') THEN !Last entry
    IDX = 1
  ELSE IF (TRIM(TFIELDLIST(IDX)%CMNHNAME)==TRIM(HMNHNAME)) THEN
    KID = IDX
    EXIT
  ELSE 
    IDX = IDX + 1
    IF (IDX>MAXFIELDS) IDX = 1
  END IF
  IF (IDX == IFIRSTGUESS) EXIT !All entries have been tested
END DO
!
IF (KID==0) THEN
  !Field not found
  KRESP = -1
  PRINT *,'WARNING: FIND_FIELD_ID_FROM_MNHNAME: field ',TRIM(HMNHNAME),' not known'
ELSE
  IFIRSTGUESS = IDX+1
  IF (IFIRSTGUESS>MAXFIELDS) IFIRSTGUESS = 1
END IF
!
END SUBROUTINE FIND_FIELD_ID_FROM_MNHNAME
!
SUBROUTINE FIELDLIST_GOTO_MODEL(KFROM, KTO)
!
USE MODD_FIELD_n
USE MODD_PRECIP_n
!
INTEGER, INTENT(IN) :: KFROM, KTO
!
!LOGICAL,SAVE :: GFIRST_CALL=.TRUE.
INTEGER :: IID,IRESP
!
PRINT *,'PW: FIELDLIST_GOTO_MODEL: ',KFROM,'->',KTO
!
! IF (GFIRST_CALL) THEN
!   !This is necessary because the first time this subroutine is called
!   !the TFIELDLIST is not yet initialized.
!   !The use of this subroutine is not useful the first timebecause the
!   !data for the fields has not yet been allocated.
!   GFIRST_CALL = .FALSE.
!   RETURN
! END IF
!
IF (.NOT.LFIELDLIST_ISINIT) THEN
  PRINT *,'WARNING: FIELDLIST_GOTO_MODEL: TFIELDLIST not yet initialized'
  RETURN
END IF
!
! Save current state for allocated arrays
!
CALL FIND_FIELD_ID_FROM_MNHNAME('UT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XUT
CALL FIND_FIELD_ID_FROM_MNHNAME('VT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XVT
CALL FIND_FIELD_ID_FROM_MNHNAME('WT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XWT
CALL FIND_FIELD_ID_FROM_MNHNAME('THT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XTHT
CALL FIND_FIELD_ID_FROM_MNHNAME('ACPRR',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X2D(KFROM)%DATA=>XACPRR
!
! Current model is set to model KTO
!
IF( KFROM/=KTO) THEN
CALL FIND_FIELD_ID_FROM_MNHNAME('UT',IID,IRESP)
XUT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('VT',IID,IRESP)
XVT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('WT',IID,IRESP)
XWT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('THT',IID,IRESP)
XTHT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('ACPRR',IID,IRESP)
XACPRR=>TFIELDLIST(IID)%TFIELD_X2D(KTO)%DATA
END IF
!
END SUBROUTINE FIELDLIST_GOTO_MODEL
!
END MODULE MODE_FIELD
