!MNH_LIC Copyright 2016 CNRS, Meteo-France and Universite Paul Sabatier
!MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
!MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!MNH_LIC for details. version 1.
MODULE MODE_FIELD
!
USE MODD_CONF, ONLY : CPROGRAM
USE MODD_PARAMETERS
!
IMPLICIT NONE
!
INTEGER,PRIVATE,PARAMETER :: MAXFIELDS = 100
INTEGER,PARAMETER :: TYPEUNDEF = -1, TYPEINT = 1, TYPELOG = 2, TYPEREAL = 3, TYPECHAR = 4
!
TYPE TFIELDPTR_L0D
  LOGICAL,              POINTER :: DATA => NULL()
END TYPE TFIELDPTR_L0D
!
TYPE TFIELDPTR_X1D
  REAL,DIMENSION(:),    POINTER :: DATA => NULL()
END TYPE TFIELDPTR_X1D
!
TYPE TFIELDPTR_X2D
  REAL,DIMENSION(:,:),  POINTER :: DATA => NULL()
END TYPE TFIELDPTR_X2D
!
TYPE TFIELDPTR_X3D
  REAL,DIMENSION(:,:,:),POINTER :: DATA => NULL()
END TYPE TFIELDPTR_X3D
!
!Structure describing the characteristics of a field
TYPE TFIELDDATA
  CHARACTER(LEN=NMNHNAMELGTMAX) :: CMNHNAME  = '' !Name of the field (for MesoNH, non CF convention)
  CHARACTER(LEN=32)  :: CSTDNAME  = '' !Standard name (CF convention)
  CHARACTER(LEN=32)  :: CLONGNAME = '' !Long name (CF convention)
  CHARACTER(LEN=32)  :: CUNITS    = '' !Canonical units (CF convention)
  CHARACTER(LEN=2)   :: CDIR      = '' !Type of the data field (XX,XY,--...)
  CHARACTER(LEN=100) :: CCOMMENT  = '' !Comment (for MesoNH, non CF convention)
  INTEGER            :: NGRID     = -1 !Localization on the model grid
  INTEGER            :: NTYPE     = TYPEUNDEF !Datatype
  INTEGER            :: NDIMS     = 0  !Number of dimensions
  !
  TYPE(TFIELDPTR_L0D),DIMENSION(:),ALLOCATABLE :: TFIELD_L0D !Pointer to the scalar logical fields (one per nested mesh)
  !
  TYPE(TFIELDPTR_X1D),DIMENSION(:),ALLOCATABLE :: TFIELD_X1D !Pointer to the real 1D fields (one per nested mesh)
  TYPE(TFIELDPTR_X2D),DIMENSION(:),ALLOCATABLE :: TFIELD_X2D !Pointer to the real 2D fields (one per nested mesh)
  TYPE(TFIELDPTR_X3D),DIMENSION(:),ALLOCATABLE :: TFIELD_X3D !Pointer to the real 3D fields (one per nested mesh)
END TYPE TFIELDDATA
!
LOGICAL,SAVE :: LFIELDLIST_ISINIT = .FALSE.
TYPE(TFIELDDATA),DIMENSION(MAXFIELDS),SAVE :: TFIELDLIST
!
CONTAINS
!
SUBROUTINE INI_FIELD_LIST(KMODEL)
!
USE MODD_CONF, ONLY: LCARTESIAN,NMODEL
!
INTEGER,INTENT(IN),OPTIONAL :: KMODEL
!
INTEGER :: IDX, IMODEL
!
!F90/95: TFIELDLIST(1) = TFIELDDATA('UT','x_wind','m s-1','XY','X_Y_Z_U component of wind (m/s)',2)
!F2003:
!TFIELDLIST(1) = TFIELDDATA(CMNHNAME='UT',CSTDNAME='x_wind',CUNITS='m s-1',CDIR='XY',&
!                           CCOMMENT='X_Y_Z_U component of wind (m/s)',NGRID=2)
!
PRINT *,'PW: INI_FIELD_LIST called'
print *,'PW: nmodel=',nmodel
IF (LFIELDLIST_ISINIT) THEN
  PRINT *,'ERROR: INI_FIELD_LIST already called'
  RETURN
END IF
LFIELDLIST_ISINIT = .TRUE.
!
IF (PRESENT(KMODEL)) THEN
  IMODEL = KMODEL
ELSE
  IMODEL = NMODEL
END IF
!
IDX = 1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'MASDEV'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH version (without bugfix)'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'BUGFIX'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH bugfix number'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'BIBUSER'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: user binary library'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'PROGRAM'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH family: used program'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'FILETYPE'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: type of this file'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'MY_NAME'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: filename (no extension)'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'DAD_NAME'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: filename of the dad file'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'DXRATIO'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: DXRATIO'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Resolution ratio between this mesh and its father in x-direction'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'DYRATIO'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: DYRATIO'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Resolution ratio between this mesh and its father in y-direction'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'XOR'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: XOR'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Horizontal position of this mesh relative to its father'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'YOR'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: YOR'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Vertical position of this mesh relative to its father'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'STORAGE_TYPE'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: STORAGE_TYPE'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Storage type for the information written in the FM files'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPECHAR
TFIELDLIST(IDX)%NDIMS      = 1
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'IMAX'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: IMAX'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'x-dimension of the physical domain'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'JMAX'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: JMAX'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'y-dimension of the physical domain'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'KMAX'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: KMAX'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'z-dimension of the physical domain'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'JPHEXT'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: JPHEXT'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Number of horizontal external points on each side'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEINT
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
!
IF (.NOT.LCARTESIAN) THEN
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'RPK'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: RPK'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Projection parameter for conformal projection'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'LONORI'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: LONORI'
TFIELDLIST(IDX)%CUNITS     = 'degree'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Longitude of the point of coordinates x=0, y=0 for conformal projection'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'LATORI'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: LATORI'
TFIELDLIST(IDX)%CUNITS     = 'degree'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Latitude of the point of coordinates x=0, y=0 for conformal projection'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
END IF
!
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'THINSHELL'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: THINSHELL'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Logical for thinshell approximation'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPELOG
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'LAT0'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: LAT0'
TFIELDLIST(IDX)%CUNITS     = 'degree'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Reference latitude for conformal projection'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'LON0'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: LON0'
TFIELDLIST(IDX)%CUNITS     = 'degree'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Reference longitude for conformal projection'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'BETA'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: BETA'
TFIELDLIST(IDX)%CUNITS     = 'degree'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Rotation angle for conformal projection'
TFIELDLIST(IDX)%NGRID      = 0
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'XHAT'
!TODO: check stdname
TFIELDLIST(IDX)%CSTDNAME   = 'projection_x_coordinate'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: XHAT'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = 'XX'
TFIELDLIST(IDX)%CCOMMENT   = 'Position x in the conformal or cartesian plane'
TFIELDLIST(IDX)%NGRID      = 2
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 1
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X1D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'YHAT'
!TODO: check stdname
TFIELDLIST(IDX)%CSTDNAME   = 'projection_y_coordinate'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: YHAT'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = 'YY'
TFIELDLIST(IDX)%CCOMMENT   = 'Position y in the conformal or cartesian plane'
TFIELDLIST(IDX)%NGRID      = 3
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 1
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X1D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'ZHAT'
!TODO: check stdname
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: ZHAT'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Height level without orography'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 1
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X1D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'ALT'
TFIELDLIST(IDX)%CSTDNAME   = 'altitude'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: ALT'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_ALTitude'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
!
IF (.NOT.LCARTESIAN) THEN
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'LAT'
TFIELDLIST(IDX)%CSTDNAME   = 'latitude'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: LAT'
TFIELDLIST(IDX)%CUNITS     = 'degree_north'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_latitude'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 2
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X2D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'LON'
TFIELDLIST(IDX)%CSTDNAME   = 'longitude'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: LON'
TFIELDLIST(IDX)%CUNITS     = 'degree_east'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_longitude'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 2
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X2D(IMODEL))
IDX = IDX+1
!
END IF
!
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'ZS'
TFIELDLIST(IDX)%CSTDNAME   = 'ground_level_altitude'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: ZS'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'orography'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 2
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X2D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'ZSMT'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: ZSMT'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'smooth orography'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 2
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X2D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'SLEVE'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: SLEVE'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Logical for SLEVE coordinate'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPELOG
TFIELDLIST(IDX)%NDIMS      = 0
ALLOCATE(TFIELDLIST(IDX)%TFIELD_L0D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'UT'
TFIELDLIST(IDX)%CSTDNAME   = 'x_wind'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: UT'
TFIELDLIST(IDX)%CUNITS     = 'm s-1'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_U component of wind (m/s)'
TFIELDLIST(IDX)%NGRID      = 2
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'VT'
TFIELDLIST(IDX)%CSTDNAME   = 'y_wind'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: VT'
TFIELDLIST(IDX)%CUNITS     = 'm s-1'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_V component of wind (m/s)'
TFIELDLIST(IDX)%NGRID      = 3
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'WT'
TFIELDLIST(IDX)%CSTDNAME   = 'upward_air_velocity'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: WT'
TFIELDLIST(IDX)%CUNITS     = 'm s-1'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_vertical wind (m/s)'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'THT'
TFIELDLIST(IDX)%CSTDNAME   = 'air_potential_temperature'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: THT'
TFIELDLIST(IDX)%CUNITS     = 'K'
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_potential temperature (K)'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'RHOREFZ'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: RHOREFZ'
TFIELDLIST(IDX)%CUNITS     = 'kg m-3'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'rhodz for reference state without orography'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 1
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X1D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'THVREFZ'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: THVREFZ'
TFIELDLIST(IDX)%CUNITS     = 'K'
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'thetavz for reference state without orography'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 1
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X1D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'EXNTOP'
TFIELDLIST(IDX)%CSTDNAME   = 'dimensionless_exner_function'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: EXNTOP'
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = '--'
TFIELDLIST(IDX)%CCOMMENT   = 'Exner function at model top'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 0
IDX = IDX+1
!
!
IF (CPROGRAM == 'MESONH') THEN
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'US_PRES'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: US_PRES'
!TODO: units?
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_US_PRES'
TFIELDLIST(IDX)%NGRID      = 2
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'VS_PRES'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: VS_PRES'
!TODO: units?
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_VS_PRES'
TFIELDLIST(IDX)%NGRID      = 3
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'WS_PRES'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: WS_PRES'
!TODO: units?
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_US_PRES'
TFIELDLIST(IDX)%NGRID      = 4
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'THS_CLD'
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: THS_CLD'
!TODO: units?
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = 'XY'
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_Z_THS_CLD'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 3
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X3D(IMODEL))
IDX = IDX+1
!
END IF
!
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = 'ACPRR'
TFIELDLIST(IDX)%CSTDNAME   = 'rainfall_amount'
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: ACPRR'
!PW: TODO: CF-convention prefers 'kg m-2'
TFIELDLIST(IDX)%CUNITS     = 'm'
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = 'X_Y_ACcumulated Precipitation Rain Rate (m)'
TFIELDLIST(IDX)%NGRID      = 1
TFIELDLIST(IDX)%NTYPE      = TYPEREAL
TFIELDLIST(IDX)%NDIMS      = 2
ALLOCATE(TFIELDLIST(IDX)%TFIELD_X2D(IMODEL))
IDX = IDX+1
!
PRINT *,'INFO: INI_FIELD_LIST: number of used fields=',IDX-1,' out of ',MAXFIELDS
!
#if 0
!
IF(IDX>MAXFIELDS) CALL ERR_INI_FIELD_LIST()
TFIELDLIST(IDX)%CMNHNAME   = ''
TFIELDLIST(IDX)%CSTDNAME   = ''
TFIELDLIST(IDX)%CLONGNAME  = 'MesoNH: '
TFIELDLIST(IDX)%CUNITS     = ''
TFIELDLIST(IDX)%CDIR       = ''
TFIELDLIST(IDX)%CCOMMENT   = ''
TFIELDLIST(IDX)%NGRID      = 
TFIELDLIST(IDX)%NTYPE      = 
TFIELDLIST(IDX)%NDIMS      = 
ALLOCATE(TFIELDLIST(IDX)%TFIELD_xxxD(IMODEL))
IDX = IDX+1
#endif
!
CONTAINS
SUBROUTINE ERR_INI_FIELD_LIST()
  PRINT *,'FATAL: INI_FIELD_LIST: IDX>MAXFIELDS (',MAXFIELDS,')'
  STOP
END SUBROUTINE ERR_INI_FIELD_LIST
!
END SUBROUTINE INI_FIELD_LIST
!
SUBROUTINE FIND_FIELD_ID_FROM_MNHNAME(HMNHNAME,KID,KRESP)
!
CHARACTER(LEN=*),            INTENT(IN) :: HMNHNAME !Name of the field to find
INTEGER,                     INTENT(OUT):: KID      !Index of the field
INTEGER,                     INTENT(OUT):: KRESP    !Return-code 
!
INTEGER :: IDX,JI
INTEGER :: ICOUNT
INTEGER,SAVE :: IFIRSTGUESS=1 !Store first field to test
!
!PW: TODO: possible optimizations:
! * Classement alphanumerique + index vers 1er champ commencant par caractere
! * Classement dans l'ordre des ecritures + stockage dernier hit + reboucler depuis le debut => DONE
!
IF (.NOT.LFIELDLIST_ISINIT) THEN
  PRINT *,'FATAL: FIND_FIELD_ID_FROM_MNHNAME: TFIELDLIST not yet initialized'
  STOP
END IF
!
KID = 0
KRESP = 0
ICOUNT = 0
IDX = IFIRSTGUESS
!
DO
  ICOUNT = ICOUNT + 1
  IF (TRIM(TFIELDLIST(IDX)%CMNHNAME)=='') THEN !Last entry
    IDX = 1
  ELSE IF (TRIM(TFIELDLIST(IDX)%CMNHNAME)==TRIM(HMNHNAME)) THEN
    KID = IDX
    EXIT
  ELSE 
    IDX = IDX + 1
    IF (IDX>MAXFIELDS) IDX = 1
  END IF
  IF (IDX == IFIRSTGUESS) EXIT !All entries have been tested
END DO
!
IF (KID==0) THEN
  !Field not found
  KRESP = -1
  PRINT *,'WARNING: FIND_FIELD_ID_FROM_MNHNAME: field ',TRIM(HMNHNAME),' not known'
ELSE
  IFIRSTGUESS = IDX+1
  IF (IFIRSTGUESS>MAXFIELDS) IFIRSTGUESS = 1
END IF
!
END SUBROUTINE FIND_FIELD_ID_FROM_MNHNAME
!
SUBROUTINE FIELDLIST_GOTO_MODEL(KFROM, KTO)
!
USE MODD_REF
!
USE MODD_FIELD_n
USE MODD_GRID_n
USE MODD_PRECIP_n
!
INTEGER, INTENT(IN) :: KFROM, KTO
!
!LOGICAL,SAVE :: GFIRST_CALL=.TRUE.
INTEGER :: IID,IRESP
!
PRINT *,'PW: FIELDLIST_GOTO_MODEL: ',KFROM,'->',KTO
!
! IF (GFIRST_CALL) THEN
!   !This is necessary because the first time this subroutine is called
!   !the TFIELDLIST is not yet initialized.
!   !The use of this subroutine is not useful the first timebecause the
!   !data for the fields has not yet been allocated.
!   GFIRST_CALL = .FALSE.
!   RETURN
! END IF
!
IF (.NOT.LFIELDLIST_ISINIT) THEN
  PRINT *,'WARNING: FIELDLIST_GOTO_MODEL: TFIELDLIST not yet initialized'
  RETURN
END IF
!
! Initialize some pointers
!
IF (KFROM == KTO) THEN
  IF (.NOT.ALLOCATED(XRHODREFZ)) THEN
    PRINT *,'FATAL: INI_FIELD_LIST: XRHODREFZ not yet allocated'
    STOP
  END IF
  CALL FIND_FIELD_ID_FROM_MNHNAME('RHOREFZ',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_X1D(KFROM)%DATA=>XRHODREFZ
  !
  IF (.NOT.ALLOCATED(XTHVREFZ)) THEN
    PRINT *,'FATAL: INI_FIELD_LIST: XTHVREFZ not yet allocated'
    STOP
  END IF
  CALL FIND_FIELD_ID_FROM_MNHNAME('THVREFZ',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_X1D(KFROM)%DATA=>XTHVREFZ
  !
  IF (.NOT.ASSOCIATED(LSLEVE)) THEN
    PRINT *,'FATAL: INI_FIELD_LIST: LSLEVE not yet associated'
    STOP
  END IF
  CALL FIND_FIELD_ID_FROM_MNHNAME('SLEVE',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_L0D(KFROM)%DATA=>LSLEVE
  !
END IF
!
! Save current state for allocated arrays
!
CALL FIND_FIELD_ID_FROM_MNHNAME('UT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XUT
CALL FIND_FIELD_ID_FROM_MNHNAME('VT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XVT
CALL FIND_FIELD_ID_FROM_MNHNAME('WT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XWT
CALL FIND_FIELD_ID_FROM_MNHNAME('THT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XTHT
IF (CPROGRAM == 'MESONH') THEN
  CALL FIND_FIELD_ID_FROM_MNHNAME('US_PRES',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XRUS_PRES
  CALL FIND_FIELD_ID_FROM_MNHNAME('VS_PRES',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XRVS_PRES
  CALL FIND_FIELD_ID_FROM_MNHNAME('WS_PRES',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XRWS_PRES
  CALL FIND_FIELD_ID_FROM_MNHNAME('THS_CLD',IID,IRESP)
  TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XRTHS_CLD
END IF
CALL FIND_FIELD_ID_FROM_MNHNAME('LAT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X2D(KFROM)%DATA=>XLAT
CALL FIND_FIELD_ID_FROM_MNHNAME('LON',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X2D(KFROM)%DATA=>XLON
CALL FIND_FIELD_ID_FROM_MNHNAME('ZS',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X2D(KFROM)%DATA=>XZS
CALL FIND_FIELD_ID_FROM_MNHNAME('ZSMT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X2D(KFROM)%DATA=>XZSMT
CALL FIND_FIELD_ID_FROM_MNHNAME('XHAT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X1D(KFROM)%DATA=>XXHAT
CALL FIND_FIELD_ID_FROM_MNHNAME('YHAT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X1D(KFROM)%DATA=>XYHAT
CALL FIND_FIELD_ID_FROM_MNHNAME('ZHAT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X1D(KFROM)%DATA=>XZHAT
CALL FIND_FIELD_ID_FROM_MNHNAME('ALT',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X3D(KFROM)%DATA=>XZZ
CALL FIND_FIELD_ID_FROM_MNHNAME('ACPRR',IID,IRESP)
TFIELDLIST(IID)%TFIELD_X2D(KFROM)%DATA=>XACPRR
!
! Current model is set to model KTO
!
IF( KFROM/=KTO) THEN
CALL FIND_FIELD_ID_FROM_MNHNAME('UT',IID,IRESP)
XUT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('VT',IID,IRESP)
XVT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('WT',IID,IRESP)
XWT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('THT',IID,IRESP)
XTHT=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
IF (CPROGRAM == 'MESONH') THEN
  CALL FIND_FIELD_ID_FROM_MNHNAME('US_PRES',IID,IRESP)
  XRUS_PRES=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
  CALL FIND_FIELD_ID_FROM_MNHNAME('VS_PRES',IID,IRESP)
  XRVS_PRES=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
  CALL FIND_FIELD_ID_FROM_MNHNAME('WS_PRES',IID,IRESP)
  XRWS_PRES=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
  CALL FIND_FIELD_ID_FROM_MNHNAME('THS_CLD',IID,IRESP)
  XRTHS_CLD=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
END IF
CALL FIND_FIELD_ID_FROM_MNHNAME('LAT',IID,IRESP)
XLAT=>TFIELDLIST(IID)%TFIELD_X2D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('LON',IID,IRESP)
XLON=>TFIELDLIST(IID)%TFIELD_X2D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('ZS',IID,IRESP)
XZS=>TFIELDLIST(IID)%TFIELD_X2D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('ZSMT',IID,IRESP)
XZSMT=>TFIELDLIST(IID)%TFIELD_X2D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('XHAT',IID,IRESP)
XXHAT=>TFIELDLIST(IID)%TFIELD_X1D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('YHAT',IID,IRESP)
XYHAT=>TFIELDLIST(IID)%TFIELD_X1D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('ZHAT',IID,IRESP)
XZHAT=>TFIELDLIST(IID)%TFIELD_X1D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('SLEVE',IID,IRESP)
LSLEVE=>TFIELDLIST(IID)%TFIELD_L0D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('ALT',IID,IRESP)
XZZ=>TFIELDLIST(IID)%TFIELD_X3D(KTO)%DATA
CALL FIND_FIELD_ID_FROM_MNHNAME('ACPRR',IID,IRESP)
XACPRR=>TFIELDLIST(IID)%TFIELD_X2D(KTO)%DATA
END IF
!
END SUBROUTINE FIELDLIST_GOTO_MODEL
!
END MODULE MODE_FIELD
