#!/bin/sh
#SBATCH -J run2_16jan
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 16            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run2_16jan.eo%j   #
#SBATCH -e run2_16jan.eo%j   #
#SBATCH -t 04:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2


export MPIRUN="Mpirun -np 16"

set -x
set -e
ls -lrt

rm -f 16JA2.?.CEN4T.*
cp EXSEG1.nam_run2 EXSEG1.nam
cp EXSEG2.nam_run2 EXSEG2.nam
time ${MPIRUN} MESONH${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_run2
mv OUTPUT_LISTING1  OUTPUT_LISTING1_run2
mv OUTPUT_LISTING2  OUTPUT_LISTING2_run2

ls -lrt

rm -f EXSEG1.nam EXSEG2.nam
rm -f file_for_xtransfer pipe_name PRESSURE REMAP*
ls -lrt

sbatch run_diag
ja
