#!/bin/sh
#SBATCH -J sparea_16jan
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o sparea_16jan.eo%j   #
#SBATCH -e sparea_16jan.eo%j   #
#SBATCH -t 00:20:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 1"

set -x
set -e

ls -lrt

rm -f 16JA1.1.CEN4T.004.spa04.???
time ${MPIRUN} SPAWNING${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_spa
mv OUTPUT_LISTING1  OUTPUT_LISTING1_spa
mv OUTPUT_LISTING2  OUTPUT_LISTING2_spa

ls -lrt


rm -f 16JAN_00_MNH2.???
cp PRE_REAL1.nam_dom2 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep
mv OUTPUT_LISTING1  OUTPUT_LISTING1_prep

ls -lrt

rm -f file_for_xtransfer pipe_name
rm -f PRE_REAL1.nam

sbatch run_mesonh2

ja
