#!/bin/sh
#SBATCH -J prep_16jan
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 20            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_16jan.eo%j   #
#SBATCH -e prep_16jan.eo%j   #
#SBATCH -t 02:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 20"

set -x
set -e
ln -sf $HOME/SAVE/GRIB_KTEST/ecmwf.EI.1998011* .
ls -lrt

rm -f 15JAN_12_MNH.???
cp PRE_REAL1.nam_1 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep1
 
ls -lrt


rm -f 15JAN_18_MNH.???
cp PRE_REAL1.nam_2 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep2

ls -lrt

rm -f 16JAN_00_MNH.???
cp PRE_REAL1.nam_3 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep3

ls -lrt


rm -f 16JAN_06_MNH.???
cp PRE_REAL1.nam_4 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep4

ls -lrt

rm -f PRE_REAL1.nam
rm -f file_for_xtransfer pipe_name
rm -f ecmwf.*
sbatch run_mesonh1
ja
