!     #########
      SUBROUTINE DIAG_TRIP_n(KLUOUT,KYEAR,KMONTH,KRUN,PDURATION,     &
                              PSURF_STO_OLD,PQDIS_OLD,PGROUND_STO_OLD, &
                              PQGF_OLD,PVEL_OLD,PHS_OLD,PFLOOD_STO_OLD,&
                              PFF_OLD,PHF_OLD,PQFR_OLD,PQRF_OLD,       &
                              PVFIN_OLD,PVFOUT_OLD,PWF_OLD,PLF_OLD,    &
                              PHSF_OLD,PQIN_OLD,PSOURCE_OLD            )  
!     ################################################################
!
!!****  *DIAG_TRIP_n*  
!!
!!    PURPOSE
!!    -------
!
!     TRIP river routing outputs.
!     
!!      
!!    AUTHOR
!!    ------
!!	B. Decharme     
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    28/05/05 
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
USE MODE_RW_TRIP
!
USE MODD_TRIP_GRID_n
USE MODD_TRIP_n,     ONLY : CGROUNDW, CVIT, LFLOODT, LPRINT_TRIP, XLEN, &
                              LDIAG_CPL,XTSTEP_COUPLING,LTRIP_DIAG_MISC  
USE MODD_DIAG_TRIP_n
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
INTEGER, INTENT(IN)             :: KLUOUT
INTEGER, INTENT(IN)             :: KYEAR
INTEGER, INTENT(IN)             :: KMONTH
INTEGER, INTENT(IN)             :: KRUN
!
REAL, INTENT(IN)                :: PDURATION 
!
REAL,DIMENSION(:,:), INTENT(IN) :: PSURF_STO_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PQDIS_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PGROUND_STO_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PQGF_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PVEL_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PHS_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PFLOOD_STO_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PFF_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PHF_OLD
!
REAL,DIMENSION(:,:), INTENT(IN) :: PQFR_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PQRF_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PVFIN_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PVFOUT_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PWF_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PLF_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PHSF_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PQIN_OLD
REAL,DIMENSION(:,:), INTENT(IN) :: PSOURCE_OLD
!
!*      0.2    declarations of local variables
!
 CHARACTER(LEN=10), PARAMETER         :: YDIAG ='TRIP_DIAG_'
 CHARACTER(LEN=6)                     :: YTIME
 CHARACTER(LEN=50)                    :: YFILE
 CHARACTER(LEN=10)                    :: YVNAME
!
REAL,DIMENSION(SIZE(XLEN,1),SIZE(XLEN,2))      :: ZWRITE
!
INTEGER :: ITNUM, ITVAL, IRUN_END
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('DIAG_TRIP_N',0,ZHOOK_HANDLE)
IRUN_END=INT(PDURATION/XTSTEP_COUPLING)
!
IF(KMONTH/=0)THEN
  WRITE(YTIME,'(i4.4,i2.2)') KYEAR, KMONTH
ELSE
  WRITE(YTIME,'(i4.4)') KYEAR
ENDIF
!
!-------------------------------------------------------------------------------
!Dailly outputs
!-------------------------------------------------------------------------------
!
IF(LDIAG_CPL)THEN
!
! * Recup diag file
!
  YFILE =YDIAG//'CPL_'//YTIME(1:LEN_TRIM(YTIME))//'.nc'
!
! * Time attribut
!
  ITNUM = KRUN
  ITVAL = KRUN
!
! * Store output in diag file
!
  YVNAME = 'SURF_STO'
  ZWRITE = (XDIAG_SURF_STO - PSURF_STO_OLD)
  CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!                
  YVNAME = 'QDIS'
  ZWRITE = (XDIAG_QDIS - PQDIS_OLD) / XTSTEP_COUPLING
  CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
  IF(LTRIP_DIAG_MISC)THEN                
    YVNAME = 'QSIN'
    ZWRITE = (XDIAG_QIN - PQIN_OLD) / XTSTEP_COUPLING
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL) 
  ENDIF
!
  IF(CGROUNDW/='DEF')THEN
!
    YVNAME = 'GROUND_STO'
    ZWRITE = (XDIAG_GROUND_STO - PGROUND_STO_OLD)
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!                
    YVNAME = 'QGF'
    ZWRITE = (XDIAG_QGF - PQGF_OLD) / XTSTEP_COUPLING 
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
  ENDIF
!
  IF(CVIT=='VAR')THEN
!
    YVNAME = 'VEL'
    ZWRITE = (XDIAG_VEL - PVEL_OLD) 
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'HSTREAM'
    ZWRITE = (XDIAG_HS - PHS_OLD)
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
  ENDIF
!
  IF(LFLOODT)THEN
!
    YVNAME = 'FFLOOD_T'
    ZWRITE = (XDIAG_FF - PFF_OLD)
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'FLOOD_STO'
    ZWRITE = (XDIAG_FLOOD_STO - PFLOOD_STO_OLD)
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'HFLOOD_T'
    ZWRITE = (XDIAG_HF - PHF_OLD)
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
    IF(LTRIP_DIAG_MISC)THEN
!
      YVNAME = 'QFR'
      ZWRITE = (XDIAG_QFR - PQFR_OLD) / XTSTEP_COUPLING
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!                
      YVNAME = 'QRF'
      ZWRITE = (XDIAG_QRF - PQRF_OLD) / XTSTEP_COUPLING
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'FSOURCE'
      ZWRITE = (XDIAG_SOURCE - PSOURCE_OLD)
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'VFIN'
      ZWRITE = (XDIAG_VFIN - PVFIN_OLD)
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'VFOUT'
      ZWRITE = (XDIAG_VFOUT - PVFOUT_OLD)
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'HSF'
      ZWRITE = (XDIAG_HSF - PHSF_OLD)
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'WF'
      ZWRITE = (XDIAG_WF - PWF_OLD)
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'LF'
      ZWRITE = (XDIAG_LF - PLF_OLD)
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)
!      
    ENDIF
!
  ENDIF
!
  IF(KRUN==IRUN_END.AND.LPRINT_TRIP)WRITE(KLUOUT,*)YFILE(1:LEN_TRIM(YFILE)),' ended successfully !'
!
ENDIF
!
!-------------------------------------------------------------------------------
!Monthly or run mean outputs
!-------------------------------------------------------------------------------
!
IF(KRUN==IRUN_END)THEN
!
! * Recup diag file
!
  YFILE =YDIAG//'RUN_'//YTIME(1:LEN_TRIM(YTIME))//'.nc' 
!
! * Store output in diag file
!
  YVNAME = 'SURF_STO'
  ZWRITE = XDIAG_SURF_STO / IRUN_END
  CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!                
  YVNAME = 'QDIS'
  ZWRITE = XDIAG_QDIS / PDURATION 
  CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
  IF(LTRIP_DIAG_MISC)THEN                
    YVNAME = 'QSIN'
    ZWRITE = XDIAG_QIN / PDURATION
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE) 
  ENDIF
!
  IF(CGROUNDW/='DEF')THEN
!
    YVNAME = 'GROUND_STO'
    ZWRITE = XDIAG_GROUND_STO / IRUN_END
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!                
    YVNAME = 'QGF'
    ZWRITE = XDIAG_QGF / PDURATION 
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
  ENDIF
!
  IF(CVIT=='VAR')THEN
!
    YVNAME = 'VEL'
    ZWRITE = XDIAG_VEL / IRUN_END
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
    YVNAME = 'HSTREAM'
    ZWRITE = XDIAG_HS / IRUN_END
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
  ENDIF
!
  IF(LFLOODT)THEN
!
    YVNAME = 'FFLOOD_T'
    ZWRITE = XDIAG_FF / IRUN_END
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
    YVNAME = 'FLOOD_STO'
    ZWRITE = XDIAG_FLOOD_STO / IRUN_END
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
    YVNAME = 'HFLOOD_T'
    ZWRITE = XDIAG_HF / IRUN_END
    CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE)        
!
    IF(LTRIP_DIAG_MISC)THEN
!
      YVNAME = 'QFR'
      ZWRITE = XDIAG_QFR / PDURATION
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!                
      YVNAME = 'QRF'
      ZWRITE = XDIAG_QRF / PDURATION
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'FSOURCE'
      ZWRITE = XDIAG_SOURCE / IRUN_END
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'VFIN'
      ZWRITE = XDIAG_VFIN / IRUN_END
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'VFOUT'
      ZWRITE = XDIAG_VFOUT / IRUN_END
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'HSF'
      ZWRITE = XDIAG_HSF / IRUN_END
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'WF'
      ZWRITE = XDIAG_WF / IRUN_END
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)        
!
      YVNAME = 'LF'
      ZWRITE = XDIAG_LF / IRUN_END
      CALL WRITE_TRIP(KLUOUT,YFILE,YVNAME,XLEN,ZWRITE,ITNUM,ITVAL)       
!
    ENDIF       
!
  ENDIF
!
  IF(LPRINT_TRIP)WRITE(KLUOUT,*)YFILE(1:LEN_TRIM(YFILE)),' ended successfully !'
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_TRIP_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
END SUBROUTINE DIAG_TRIP_n
