!SURFEX_LIC Copyright 1994-2014 Meteo-France 
!SURFEX_LIC This is part of the SURFEX software governed by the CeCILL-C  licence
!SURFEX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!SURFEX_LIC for details. version 1.
SUBROUTINE GOTO_WRAPPER_SEAFLUX(KFROM,KTO, LKFROM)
USE MODD_CH_SEAFLUX_n
USE MODD_DIAG_SEAFLUX_n
USE MODD_SEAFLUX_GRID_n
USE MODD_SEAFLUX_n
USE MODD_DATA_SEAFLUX_n
USE MODD_SEAFLUX_SBL_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_SEAFLUX',0,ZHOOK_HANDLE)
 CALL CH_SEAFLUX_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_SEAFLUX_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SEAFLUX_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SEAFLUX_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DATA_SEAFLUX_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SEAFLUX_SBL_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_SEAFLUX',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_SEAFLUX
