SUBROUTINE GOTO_WRAPPER_ISBA(KFROM,KTO, LKFROM)
USE MODD_CH_ISBA_n
USE MODD_DIAG_EVAP_ISBA_n
USE MODD_DIAG_ISBA_n
USE MODD_DIAG_MISC_ISBA_n
USE MODD_GR_BIOG_n
USE MODD_ISBA_GRID_n
USE MODD_ISBA_n
USE MODD_DATA_ISBA_n
USE MODD_DATA_TSZ0_n
USE MODD_DST_n
USE MODD_SLT_n
USE MODD_AGRI_n
USE MODD_ISBA_CANOPY_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_ISBA',0,ZHOOK_HANDLE)
 CALL CH_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_EVAP_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_MISC_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL GR_BIOG_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL ISBA_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DATA_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DATA_TSZ0_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DST_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SLT_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL AGRI_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL ISBA_CANOPY_GOTO_MODEL(KFROM, KTO, LKFROM)


IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_ISBA',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_ISBA
