SUBROUTINE GOTO_WRAPPER_FLAKE(KFROM,KTO, LKFROM)
USE MODD_DIAG_MISC_FLAKE_n
USE MODD_DIAG_FLAKE_n
USE MODD_FLAKE_GRID_n
USE MODD_FLAKE_n
USE MODD_FLAKE_SBL_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
INTEGER,INTENT(IN) :: KFROM,KTO
LOGICAL, INTENT(IN) :: LKFROM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_FLAKE',0,ZHOOK_HANDLE)
 CALL DIAG_MISC_FLAKE_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_FLAKE_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL FLAKE_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL FLAKE_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL FLAKE_SBL_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_FLAKE',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_FLAKE
