SUBROUTINE GOTO_TEB(KPATCH)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODE_MODELN_TEB_HANDLER
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KPATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!
IF (LHOOK) CALL DR_HOOK('GOTO_TEB',0,ZHOOK_HANDLE)
 CALL GOTO_PATCH_TEB(KPATCH)
IF (LHOOK) CALL DR_HOOK('GOTO_TEB',1,ZHOOK_HANDLE)
!!
END SUBROUTINE GOTO_TEB
