!SURFEX_LIC Copyright 1994-2014 Meteo-France 
!SURFEX_LIC This is part of the SURFEX software governed by the CeCILL-C  licence
!SURFEX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!SURFEX_LIC for details. version 1.
SUBROUTINE GOTO_SURFEX(KMI, LKFROM)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODE_MODELN_SURFEX_HANDLER
!
IMPLICIT NONE
!
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KMI
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!
IF (LHOOK) CALL DR_HOOK('GOTO_SURFEX',0,ZHOOK_HANDLE)
 CALL GOTO_MODEL_SURFEX(KMI, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_SURFEX',1,ZHOOK_HANDLE)
!!
END SUBROUTINE GOTO_SURFEX
