!SURFEX_LIC Copyright 1994-2014 Meteo-France 
!SURFEX_LIC This is part of the SURFEX software governed by the CeCILL-C  licence
!SURFEX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!SURFEX_LIC for details. version 1.
MODULE MODI_GOTO_WRAPPER_TEB
  INTERFACE
     SUBROUTINE GOTO_WRAPPER_TEB(KFROM,KTO, LKFROM, KTO_PATCH)
       !
       IMPLICIT NONE 
       LOGICAL, INTENT(IN) :: LKFROM
       INTEGER,INTENT(IN) :: KFROM,KTO
       INTEGER,INTENT(IN) :: KTO_PATCH
       !
     END SUBROUTINE GOTO_WRAPPER_TEB
  END INTERFACE
END MODULE MODI_GOTO_WRAPPER_TEB

SUBROUTINE GOTO_WRAPPER_TEB(KFROM,KTO, LKFROM, KTO_PATCH)
USE MODD_CH_TEB_n
USE MODD_DIAG_MISC_TEB_n
USE MODD_DIAG_UTCI_TEB_n
USE MODD_DIAG_TEB_n
USE MODD_TEB_GRID_n
USE MODD_TEB_n
USE MODD_TEB_VEG_n
USE MODD_BEM_n
USE MODD_DATA_BEM_n
USE MODD_DATA_TEB_n
USE MODD_BLD_DESCRIPTION
USE MODD_DATA_TEB_GARDEN_n
USE MODD_DATA_TEB_GREENROOF_n
USE MODD_TEB_CANOPY_n
USE MODD_TEB_GARDEN_n
USE MODD_TEB_GREENROOF_n
USE MODD_GR_BIOG_GARDEN_n
!
USE MODE_MODELN_TEB_HANDLER, ONLY : GET_CURRENT_PATCH_INDEX_TEB, &
                                    PUT_CURRENT_PATCH_INDEX_TEB
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
INTEGER,INTENT(IN) :: KTO_PATCH
!
INTEGER            :: ICURRENT_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB',0,ZHOOK_HANDLE)
ICURRENT_PATCH = GET_CURRENT_PATCH_INDEX_TEB()

 CALL TEB_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_VEG_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL BEM_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GARDEN_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_MISC_TEB_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_UTCI_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GREENROOF_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
!
 CALL CH_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_MISC_TEB_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL DIAG_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL BEM_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL BLD_DESC_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DATA_BEM_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DATA_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DATA_TEB_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GARDEN_PGD_EVOL_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL DATA_TEB_GREENROOF_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GREENROOF_PGD_EVOL_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL TEB_CANOPY_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL TEB_GARDEN_PGD_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TEB_GREENROOF_GOTO_MODEL(KFROM, KTO, LKFROM, ICURRENT_PATCH, KTO_PATCH)
 CALL TEB_GREENROOF_PGD_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL GR_BIOG_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
!
 CALL PUT_CURRENT_PATCH_INDEX_TEB(KTO_PATCH)
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TEB
