!SURFEX_LIC Copyright 1994-2014 Meteo-France 
!SURFEX_LIC This is part of the SURFEX software governed by the CeCILL-C  licence
!SURFEX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!SURFEX_LIC for details. version 1.
SUBROUTINE GOTO_WRAPPER_IDEAL(KFROM,KTO, LKFROM)
USE MODD_DIAG_IDEAL_n
USE MODD_IDEAL_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_IDEAL',0,ZHOOK_HANDLE)
 CALL DIAG_IDEAL_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL IDEAL_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_IDEAL',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_IDEAL
