SUBROUTINE GOTO_WRAPPER_TRIP(KFROM,KTO, LKFROM)
USE MODD_TRIP_n
USE MODD_DIAG_TRIP_n
USE MODD_TRIP_GRID_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
INTEGER,INTENT(IN) :: KFROM,KTO
LOGICAL, INTENT(IN) :: LKFROM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TRIP',0,ZHOOK_HANDLE)
 CALL TRIP_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_TRIP_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL TRIP_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TRIP',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TRIP
