!SURFEX_LIC Copyright 1994-2014 Meteo-France 
!SURFEX_LIC This is part of the SURFEX software governed by the CeCILL-C  licence
!SURFEX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!SURFEX_LIC for details. version 1.
SUBROUTINE GOTO_WRAPPER_SURFATM(KFROM,KTO, LKFROM)
USE MODD_DATA_COVER_n
USE MODD_CH_EMIS_FIELD_n
USE MODD_CH_SNAP_n
USE MODD_CH_SURF_n
USE MODD_DIAG_SURF_ATM_n
USE MODD_DUMMY_SURF_FIELDS_n
USE MODD_EMIS_GR_FIELD_n
USE MODD_SURF_ATM_GRID_n
USE MODD_SURF_ATM_n
USE MODD_SURF_ATM_SSO_n
USE MODD_SV_n
USE MODD_IO_BUFF_n
USE MODD_SSO_CANOPY_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_SURFATM',0,ZHOOK_HANDLE)
 CALL DATA_COVER_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL CH_EMIS_FIELD_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL CH_EMIS_SNAP_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL CH_SURF_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DIAG_SURF_ATM_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL DUMMY_SURF_FIELDS_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL EMIS_GR_FIELD_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SURF_ATM_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SURF_ATM_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SURF_ATM_SSO_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SV_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL IO_BUFF_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL SSO_CANOPY_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_SURFATM',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_SURFATM
