!##################
MODULE MODD_TRIP_GRID_n
!##################
!
!!****  *MODD_TRIP_GRID_n - declaration of grid for TRIP scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	B. Decharme   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       05/2008
!
!*       0.   DECLARATIONS
!             ------------
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE TRIP_GRID_t
!-------------------------------------------------------------------------------
!
! Grid definition
!
  REAL, POINTER,  DIMENSION(:)      :: XGRID_TRIP ! lits of parameters used to define the grid
!
!-------------------------------------------------------------------------------
!
  REAL, POINTER, DIMENSION(:,:)    :: XAREA       ! 2d grid area [m*m]
!
!
  LOGICAL, POINTER, DIMENSION(:,:) :: GMASK       !Logical Mask for TRIP grid
!
!-------------------------------------------------------------------------------
!
END TYPE TRIP_GRID_t
!
TYPE(TRIP_GRID_t), ALLOCATABLE, TARGET, SAVE :: TRIP_GRID_MODEL(:)
!
REAL, POINTER,    DIMENSION(:)   :: XGRID_TRIP=>NULL()
!$OMP THREADPRIVATE(XGRID_TRIP)
REAL, POINTER,    DIMENSION(:,:) :: XAREA=>NULL()
!$OMP THREADPRIVATE(XAREA)
LOGICAL, POINTER, DIMENSION(:,:) :: GMASK=>NULL() 
!$OMP THREADPRIVATE(GMASK)
!
CONTAINS

SUBROUTINE TRIP_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
!
! Save current state for allocated arrays
IF (LKFROM) THEN
TRIP_GRID_MODEL(KFROM)%XGRID_TRIP=>XGRID_TRIP
TRIP_GRID_MODEL(KFROM)%XAREA=>XAREA
TRIP_GRID_MODEL(KFROM)%GMASK=>GMASK
ENDIF
!
! Current model is set to model KTO
XGRID_TRIP=>TRIP_GRID_MODEL(KTO)%XGRID_TRIP
XAREA=>TRIP_GRID_MODEL(KTO)%XAREA
GMASK=>TRIP_GRID_MODEL(KTO)%GMASK
!
END SUBROUTINE TRIP_GRID_GOTO_MODEL

SUBROUTINE TRIP_GRID_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_GRID_N:TRIP_GRID_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(TRIP_GRID_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(TRIP_GRID_MODEL(J)%XGRID_TRIP)
  NULLIFY(TRIP_GRID_MODEL(J)%XAREA)
  NULLIFY(TRIP_GRID_MODEL(J)%GMASK)
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_GRID_N:TRIP_GRID_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE TRIP_GRID_ALLOC

SUBROUTINE TRIP_GRID_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_GRID_N:TRIP_GRID_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(TRIP_GRID_MODEL)) DEALLOCATE(TRIP_GRID_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_GRID_N:TRIP_GRID_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE TRIP_GRID_DEALLO

END MODULE MODD_TRIP_GRID_n
