!######################
MODULE MODD_DIAG_TRIP_n
!######################
!
!!****  *MODD_DIAG_TRIP - declaration of diagnostics for TRIP scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	B. Decharme   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       21/05/08
!
!*       0.   DECLARATIONS
!             ------------
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE DIAG_TRIP_t
!-------------------------------------------------------------------------------
!
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_SURF_STO   ! River storage             [kg m-2]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_GROUND_STO ! Groundwater storage       [kg m-2]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_FLOOD_STO  ! Floodplains storage       [kg m-2]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_QDIS       ! Discharge                 [m3 s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_QGF        ! Groundwater flow to river [m3 s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_VEL        ! Stream flow velocity      [m s-1 ]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_HS         ! Stream river depth        [m     ]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_FF         ! TRIP flooded fraction     [-]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_HF         ! Flood depth               [m     ]
!
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_QFR        ! Flood flow to river          [m3 s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_QRF        ! River flow to floodplain     [m3 s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_QIN        ! Inflow to the river          [m3 s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_VFIN       ! River flow to flood velocity [m s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_VFOUT      ! Flood flow to river velocity [m s-1]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_WF         ! Flood width during dt        [m]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_LF         ! Flood lenght during dt       [m]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_HSF        ! River-Flood depth comparison [m]
  REAL, POINTER, DIMENSION(:,:) :: XDIAG_SOURCE     ! Floodplains source (Pf-Ef-If)[kg m-2]
!
!-------------------------------------------------------------------------------
!
END TYPE DIAG_TRIP_t
!
TYPE(DIAG_TRIP_t), ALLOCATABLE, TARGET, SAVE :: DIAG_TRIP_MODEL(:)
!
REAL, POINTER, DIMENSION(:,:) :: XDIAG_SURF_STO=>NULL()           
!$OMP THREADPRIVATE(XDIAG_SURF_STO)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_GROUND_STO=>NULL()          
!$OMP THREADPRIVATE(XDIAG_GROUND_STO)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_FLOOD_STO=>NULL()          
!$OMP THREADPRIVATE(XDIAG_FLOOD_STO)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_QDIS=>NULL()      
!$OMP THREADPRIVATE(XDIAG_QDIS)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_QGF=>NULL()         
!$OMP THREADPRIVATE(XDIAG_QGF)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_VEL=>NULL()             
!$OMP THREADPRIVATE(XDIAG_VEL)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_HS=>NULL()       
!$OMP THREADPRIVATE(XDIAG_HS)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_FF=>NULL()
!$OMP THREADPRIVATE(XDIAG_FF)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_HF=>NULL()        
!$OMP THREADPRIVATE(XDIAG_HF)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_QFR=>NULL()      
!$OMP THREADPRIVATE(XDIAG_QFR)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_QRF=>NULL()       
!$OMP THREADPRIVATE(XDIAG_QRF)
!
REAL, POINTER, DIMENSION(:,:) :: XDIAG_QIN=>NULL()
!$OMP THREADPRIVATE(XDIAG_QIN)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_VFIN=>NULL()
!$OMP THREADPRIVATE(XDIAG_VFIN)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_VFOUT=>NULL()
!$OMP THREADPRIVATE(XDIAG_VFOUT)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_WF=>NULL()
!$OMP THREADPRIVATE(XDIAG_WF)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_LF=>NULL()
!$OMP THREADPRIVATE(XDIAG_LF)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_HSF=>NULL()
!$OMP THREADPRIVATE(XDIAG_HSF)
REAL, POINTER, DIMENSION(:,:) :: XDIAG_SOURCE=>NULL()
!$OMP THREADPRIVATE(XDIAG_SOURCE)
!
CONTAINS
!
SUBROUTINE DIAG_TRIP_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
!
! Save current state for allocated arrays
IF (LKFROM) THEN
DIAG_TRIP_MODEL(KFROM)%XDIAG_SURF_STO=>XDIAG_SURF_STO
DIAG_TRIP_MODEL(KFROM)%XDIAG_GROUND_STO=>XDIAG_GROUND_STO
DIAG_TRIP_MODEL(KFROM)%XDIAG_FLOOD_STO=>XDIAG_FLOOD_STO
DIAG_TRIP_MODEL(KFROM)%XDIAG_QDIS=>XDIAG_QDIS
DIAG_TRIP_MODEL(KFROM)%XDIAG_QGF=>XDIAG_QGF
DIAG_TRIP_MODEL(KFROM)%XDIAG_VEL=>XDIAG_VEL
DIAG_TRIP_MODEL(KFROM)%XDIAG_HS=>XDIAG_HS
DIAG_TRIP_MODEL(KFROM)%XDIAG_FF=>XDIAG_FF
DIAG_TRIP_MODEL(KFROM)%XDIAG_HF=>XDIAG_HF
!
DIAG_TRIP_MODEL(KFROM)%XDIAG_QFR=>XDIAG_QFR
DIAG_TRIP_MODEL(KFROM)%XDIAG_QRF=>XDIAG_QRF
DIAG_TRIP_MODEL(KFROM)%XDIAG_QIN=>XDIAG_QIN
DIAG_TRIP_MODEL(KFROM)%XDIAG_VFIN=>XDIAG_VFIN
DIAG_TRIP_MODEL(KFROM)%XDIAG_VFOUT=>XDIAG_VFOUT
DIAG_TRIP_MODEL(KFROM)%XDIAG_WF=>XDIAG_WF
DIAG_TRIP_MODEL(KFROM)%XDIAG_LF=>XDIAG_LF
DIAG_TRIP_MODEL(KFROM)%XDIAG_HSF=>XDIAG_HSF
DIAG_TRIP_MODEL(KFROM)%XDIAG_SOURCE=>XDIAG_SOURCE
ENDIF
!
! Current model is set to model KTO
XDIAG_SURF_STO=>DIAG_TRIP_MODEL(KTO)%XDIAG_SURF_STO
XDIAG_GROUND_STO=>DIAG_TRIP_MODEL(KTO)%XDIAG_GROUND_STO
XDIAG_FLOOD_STO=>DIAG_TRIP_MODEL(KTO)%XDIAG_FLOOD_STO
XDIAG_QDIS=>DIAG_TRIP_MODEL(KTO)%XDIAG_QDIS
XDIAG_QGF=>DIAG_TRIP_MODEL(KTO)%XDIAG_QGF
XDIAG_VEL=>DIAG_TRIP_MODEL(KTO)%XDIAG_VEL
XDIAG_HS=>DIAG_TRIP_MODEL(KTO)%XDIAG_HS
XDIAG_FF=>DIAG_TRIP_MODEL(KTO)%XDIAG_FF
XDIAG_HF=>DIAG_TRIP_MODEL(KTO)%XDIAG_HF
!
XDIAG_QFR=>DIAG_TRIP_MODEL(KTO)%XDIAG_QFR
XDIAG_QRF=>DIAG_TRIP_MODEL(KTO)%XDIAG_QRF
XDIAG_QIN=>DIAG_TRIP_MODEL(KTO)%XDIAG_QIN
XDIAG_VFIN=>DIAG_TRIP_MODEL(KTO)%XDIAG_VFIN
XDIAG_VFOUT=>DIAG_TRIP_MODEL(KTO)%XDIAG_VFOUT
XDIAG_WF=>DIAG_TRIP_MODEL(KTO)%XDIAG_WF
XDIAG_LF=>DIAG_TRIP_MODEL(KTO)%XDIAG_LF
XDIAG_HSF=>DIAG_TRIP_MODEL(KTO)%XDIAG_HSF
XDIAG_SOURCE=>DIAG_TRIP_MODEL(KTO)%XDIAG_SOURCE
!
END SUBROUTINE DIAG_TRIP_GOTO_MODEL

SUBROUTINE DIAG_TRIP_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_TRIP_N:DIAG_TRIP_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(DIAG_TRIP_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_SURF_STO)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_GROUND_STO)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_FLOOD_STO)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_QDIS)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_QGF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_VEL)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_HS)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_FF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_HF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_QFR)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_QRF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_QIN)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_VFIN)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_VFOUT)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_WF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_LF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_HSF)
  NULLIFY(DIAG_TRIP_MODEL(J)%XDIAG_SOURCE)
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_TRIP_N:DIAG_TRIP_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_TRIP_ALLOC

SUBROUTINE DIAG_TRIP_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_TRIP_N:DIAG_TRIP_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(DIAG_TRIP_MODEL)) DEALLOCATE(DIAG_TRIP_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_TRIP_N:DIAG_TRIP_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_TRIP_DEALLO
!
END MODULE MODD_DIAG_TRIP_n
