MODULE MODD_SPLINES

INTEGER, PARAMETER :: NMAX=2000
INTEGER, PARAMETER :: NORDMAX=2
INTEGER, PARAMETER :: NSDMAX=20

REAL, DIMENSION(:,:,:), ALLOCATABLE :: AI
INTEGER, DIMENSION(:,:), ALLOCATABLE :: NS
REAL, DIMENSION(:,:,:), ALLOCATABLE :: ZS
REAL, DIMENSION(:,:,:,:), ALLOCATABLE:: XS

END MODULE MODD_SPLINES
