MODULE MODE_MODELN_TEB_HANDLER
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 

INTEGER, SAVE, PRIVATE :: ICURRENT_PATCH = 1
!$OMP THREADPRIVATE(ICURRENT_PATCH)

CONTAINS 

FUNCTION GET_CURRENT_PATCH_INDEX_TEB()
INTEGER :: GET_CURRENT_PATCH_INDEX_TEB
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_TEB_HANDLER:GET_CURRENT_PATCH_INDEX_TEB',0,ZHOOK_HANDLE)
GET_CURRENT_PATCH_INDEX_TEB = ICURRENT_PATCH
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_TEB_HANDLER:GET_CURRENT_PATCH_INDEX_TEB',1,ZHOOK_HANDLE)
!!
END FUNCTION GET_CURRENT_PATCH_INDEX_TEB

SUBROUTINE PUT_CURRENT_PATCH_INDEX_TEB(KPATCH)
INTEGER, INTENT(IN) :: KPATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_TEB_HANDLER:PUT_CURRENT_PATCH_INDEX_TEB',0,ZHOOK_HANDLE)
ICURRENT_PATCH = KPATCH
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_TEB_HANDLER:PUT_CURRENT_PATCH_INDEX_TEB',1,ZHOOK_HANDLE)
!!
END SUBROUTINE PUT_CURRENT_PATCH_INDEX_TEB

SUBROUTINE GOTO_PATCH_TEB(KPATCH)
!
USE MODI_GOTO_WRAPPER_TEB
USE MODE_MODELN_SURFEX_HANDLER, ONLY : GET_CURRENT_MODEL_INDEX_SURFEX
!
INTEGER, INTENT(IN) :: KPATCH
INTEGER             :: ICURRENT_MODEL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_TEB_HANDLER:GOTO_PATCH_TEB',0,ZHOOK_HANDLE)

ICURRENT_MODEL = GET_CURRENT_MODEL_INDEX_SURFEX()
!
 CALL GOTO_WRAPPER_TEB    (ICURRENT_MODEL, ICURRENT_MODEL, .TRUE., KPATCH)
!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_TEB_HANDLER:GOTO_PATCH_TEB',1,ZHOOK_HANDLE)
!!
END SUBROUTINE GOTO_PATCH_TEB

END MODULE MODE_MODELN_TEB_HANDLER

