!SURFEX_LIC Copyright 1994-2014 Meteo-France 
!SURFEX_LIC This is part of the SURFEX software governed by the CeCILL-C  licence
!SURFEX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!SURFEX_LIC for details. version 1.
!     #########
SUBROUTINE READ_NAMELISTS_WATFLUX_n(HPROGRAM,HINIT)
!     #######################################################
!
! --------------------------------------------------------------------------
!
USE MODN_WATFLUX_n
!
USE MODI_DEFAULT_WATFLUX
USE MODI_DEFAULT_CH_DEP
USE MODI_DEFAULT_DIAG_WATFLUX
USE MODI_READ_DEFAULT_WATFLUX_n
USE MODi_READ_WATFLUX_CONF_n
!
USE MODI_READ_NAM_PREP_WATFLUX_n
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODI_READ_WATFLUX_CONF_n
IMPLICIT NONE
!
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HINIT     ! choice of fields to initialize
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-----------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('READ_NAMELISTS_WATFLUX_N',0,ZHOOK_HANDLE)
 CALL DEFAULT_WATFLUX(XTSTEP,XOUT_TSTEP,CWAT_ALB,CINTERPOL_TS)
!
 CALL DEFAULT_CH_DEP(CCH_DRY_DEP)
!
 CALL DEFAULT_DIAG_WATFLUX(N2M,LSURF_BUDGET,L2M_MIN_ZS,LRAD_BUDGET,LCOEF,LSURF_VARS, &
                           LSURF_BUDGETC,LRESET_BUDGETC,XDIAG_TSTEP        )
!
 CALL READ_DEFAULT_WATFLUX_n(HPROGRAM)
!
 CALL READ_WATFLUX_CONF_n(HPROGRAM)
!
!----------------------------------------------------------------------------
!
IF (HINIT=='PRE') CALL READ_NAM_PREP_WATFLUX_n(HPROGRAM)
IF (LHOOK) CALL DR_HOOK('READ_NAMELISTS_WATFLUX_N',1,ZHOOK_HANDLE)
!
END SUBROUTINE READ_NAMELISTS_WATFLUX_n
