!     #########
SUBROUTINE READ_NAM_PREP_GARDEN_n(HPROGRAM)
!     #######################################################
!
!----------------------------------------------
!
USE MODN_PREP_GARDEN_SNOW
USE MODN_PREP_TEB_GARDEN
!
USE MODD_SURF_PAR, ONLY : XUNDEF, NUNDEF
!
USE MODI_DEFAULT_PREP_TEB_GARDEN
USE MODI_READ_PREP_GARDEN_SNOW
!
USE MODI_TEST_NAM_VAR_SURF
USE MODI_GET_LUOUT
USE MODI_OPEN_NAMELIST
USE MODI_CLOSE_NAMELIST
USE MODE_POS_SURF
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
!
INTEGER :: ILUNAM         ! logical unit of namelist file
INTEGER :: ILUOUT
LOGICAL :: GFOUND         ! Return code when searching namelist
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!---------------------------------------
!
IF (LHOOK) CALL DR_HOOK('READ_NAM_PREP_GARDEN_N',0,ZHOOK_HANDLE)
 CALL DEFAULT_PREP_TEB_GARDEN
!
 CALL GET_LUOUT(HPROGRAM,ILUOUT)
!
 CALL OPEN_NAMELIST(HPROGRAM,ILUNAM)
 CALL POSNAM(ILUNAM,'NAM_PREP_TEB_GARDEN',GFOUND,ILUOUT)
IF (GFOUND) READ(UNIT=ILUNAM,NML=NAM_PREP_TEB_GARDEN)
 CALL CLOSE_NAMELIST(HPROGRAM,ILUNAM)
!
 CALL TEST_NAM_VAR_SURF(ILUOUT,'CTYPE',    CTYPE,   '      ', 'GRIB  ','MESONH','ASCII ','LFI   ')
 CALL TEST_NAM_VAR_SURF(ILUOUT,'CTYPEPGD', CTYPEPGD,'      ', 'GRIB  ','MESONH','ASCII ','LFI   ')
 CALL TEST_NAM_VAR_SURF(ILUOUT,'CTYPE_HUG',CTYPE_HUG,'      ','GRIB  ','MESONH','ASCII ','ASCLLV')
 CALL TEST_NAM_VAR_SURF(ILUOUT,'CTYPE_TG', CTYPE_TG,'      ', 'GRIB  ','MESONH','ASCII ','ASCLLV')
!
 CALL READ_PREP_GARDEN_SNOW(HPROGRAM,CSNOW,NSNOW_LAYER)
IF (LHOOK) CALL DR_HOOK('READ_NAM_PREP_GARDEN_N',1,ZHOOK_HANDLE)
!
!------------------------------------
!
END SUBROUTINE READ_NAM_PREP_GARDEN_n
