SUBROUTINE SECOND_SFX(KT)
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
INTEGER :: KT
INTEGER :: IT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('SECOND_SFX',0,ZHOOK_HANDLE)
 CALL system('date +%s > tempo')
OPEN(UNIT=99,FILE='tempo')
READ(99,*)IT
CLOSE(99)
KT=IT
IF (LHOOK) CALL DR_HOOK('SECOND_SFX',1,ZHOOK_HANDLE)
END SUBROUTINE SECOND_SFX
