SUBROUTINE SET_SURFEX_FILE_NAME_ASC(HNAME_IN,HNAME_OUT)
!
USE MODD_IO_SURF_ASC, ONLY : CFILEIN
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=28), OPTIONAL, INTENT(IN)     :: HNAME_IN
 CHARACTER(LEN=28), OPTIONAL, INTENT(OUT)    :: HNAME_OUT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('SET_SURFEX_FILE_NAME_ASC',0,ZHOOK_HANDLE)
!
IF (PRESENT(HNAME_IN)) THEN
  CFILEIN=HNAME_IN
ELSEIF (PRESENT(HNAME_OUT)) THEN
  HNAME_OUT=CFILEIN
ENDIF
!
IF (LHOOK) CALL DR_HOOK('SET_SURFEX_FILE_NAME_ASC',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_SURFEX_FILE_NAME_ASC
