#!/bin/sh
#SBATCH -J icart2m
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 4            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run_icart.eo%j   #
#SBATCH -e run_icart.eo%j   #
#SBATCH -t 06:00:00    # time limit

. /home/cnrm_other/ge/mrmh/rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

ln -sf $HOME/SAVE/GRIB_KTEST/CHARMEX/CHIMIE_FILES/tuv531/DATAE1 .
ln -sf $HOME/SAVE/GRIB_KTEST/CHARMEX/CHIMIE_FILES/tuv531/DATAJ1 .

cp EXSEG1.nam.src EXSEG1.nam
cp EXSEG2.nam.src EXSEG2.nam
ln -sf  ../008_preal2/ICART.1.SEG01.003.2.* .
ln -sf  ../005_preal1_18/CPLCH20040810.18.* .
ln -sf  ../006_mesonh1/ICART.1.SEG01.003.* .
ln -sf ../003_nest/ICARTT1008_PGD_2km5.neste1.* .
ln -sf ../003_nest/ICARTT1008_PGD_15km.neste1.* .

export MPIRUN="Mpirun -np 4"

time ${MPIRUN} MESONH${XYZ}

cd ../010_diag
sbatch run_diag_xyz
