#!/bin/sh

#PGD SIMU2 domaine 3, premier de la SIMU2 surlequel on interpole
ln -sf ../003_prep_nest_pgd/PGD3*neste* .

#PGD SIMU1 domaine 2 (du fichier qu'on interpole)
ln -sf ../../SIMU1/003_prep_nest_pgd/PGD2*neste* .

#Fichier atmospheric de la SIMU1 domaine 2 dont les champs atmospheriques sont interpoles sur le PGD3
ln -sf ../004_spawning_d2tod3_INIT//CLUS0.2.SPRIN.001.spa00.* .

#Fichier SIMU1 domaine 2 qu'on interpole pour les champs de surface
ln -sf ../../SIMU1/007_run/CLUS0.2.SPRIN.001.* .

time ${MONORUN} PREP_REAL_CASE${XYZ}
