#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ${SRC_MESONH}/src/LIB/Python/* .
ln -sf ../002_mesonh/XPREF.1.SEG01.000.nc .

python3 plot_014_LIMA.py
${POSTRUN} convert *.png 014_LIMA.pdf
${POSTRUN} evince 014_LIMA.pdf
