#!/bin/sh
#SBATCH -J prep_fanny
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 4            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_fanny.eo%j   #
#SBATCH -e prep_fanny.eo%j   #
#SBATCH -t 00:45:00    # time limit

. /home/cnrm_other/ge/mrmh/rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2 

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

rm -f ICART* CPLCH20040810.12.* OUTPUT_LISTING* pipe*
ln -sf ../003_nest/ICARTT1008_PGD_15km.neste1.* .
ln -sf $HOME/SAVE/GRIB_KTEST/ecmwf.OD.20040810.12 .
ln -sf $HOME/SAVE/GRIB_KTEST/mocage.GLOB22.20040810.12 .
export MPIRUN="Mpirun -np 4"

time ${MPIRUN} PREP_REAL_CASE${XYZ}

cd ../005_preal1_18
sbatch run_preal1_18_xyz
