#!/bin/ksh
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
##########################################################
#                                                        #
# ENVIRONEMMENT CONFIGURATION FOR MESONH                 #
#                                                        #
##########################################################
if [ "$SRC_MESONH" != "" ] 
then
##########################################################
#                                                        #
# ENVIRONEMENT MESONH ALLREADY SET                       #
#                                                        #
##########################################################
echo 
echo '--->' WARNING :: "profile_mesonh"
echo '--->' vous avez deja initialise votre variable d environnement '$SRC_MESONH'
echo '--->' '$SRC_MESONH="'$SRC_MESONH'"'
echo '--->' '"check your environnment profile_mesonh" !!!! '
echo 
fi
##########################################################
#                                                        #
# SOME SETTING FOR MESONH                                #
#                                                        #
##########################################################
#
# SRC_MESONH : default path to mesonh sources 
#              MUST BE SET TO YOUR OWN MESONH PATH
#
export SRC_MESONH="/home/escj/DEV64/MNH-V5-1-0"   
#
#  Version MESONH PACKAGE :: PACK-MNH-V5-1-0 : 11/12/2013
#
export VERSION_XYZ=MNH-V5-1-0
#
#  Target Architecture/compiler Machine <=> Rules.*.mk files
#
#export ARCH=LXgfortran,LXifort,LXpgi,AIX64,SX8,BGQ
#
export ARCH=LXgfortran
#
#  Version of MPI
#
#export VER_MPI=MPIVIDE,MPIAUTO,MPIICE,MPIINTEL
#
export VER_MPI=MPIVIDE
#
# OPTIMIZATION LEVEL
#
#export OPTLEVEL=DEBUG,O2
#
export OPTLEVEL=DEBUG
#
#  USER VERSION
#
export VER_USER=
#
#  NETCDF OUTPUT
#
export MNH_NCWRIT=
#
# 'Scandollar' Post Processing default variables
#
export CONF_DOLLAR=/home/escj/DEV64/MNH-V5-1-0/conf/post/confdollar_aeropc_default
#
# Version of NETCDF
#
export VER_CDF=CDFAUTO
export VERSION_CDF=3.6.3
#
# Version of GRIBAPI
#
export VER_GRIBAPI=
export VERSION_GRIBAPI=1.9.9
#
# Version of Def integer
#
export MNH_INT=I4
#
# Version of Def Real
#
export MNH_REAL=
#
##########################################################
##########################################################
##########################################################
#                                                        #
#    DONT MODIFY LINES AFTER THIS  !!!!!!!!!!!!!         #         
#                                                        #
##########################################################
##########################################################
##########################################################
#
export XYZ="-${ARCH}${MNH_REAL:+${MNH_REAL}}${MNH_INT}-${VERSION_XYZ}${VER_USER:+-${VER_USER}}-${VER_MPI}-${OPTLEVEL}"
#[ "x${VER_USER}" != "x" ] && export XYZ="${XYZ}-${VER_USER}"
# PATH to find tools like "makegen, etc ..."
export BIN_TOOLS=X86_64
export PATH=.:$SRC_MESONH/bin:$SRC_MESONH/exe:$SRC_MESONH/bin_tools/${BIN_TOOLS}:$PATH
#
# NCARG_ROOT : for use of graphic tools : diaprog 
# 
#  The "lib" and "bin" directory version 
#  are include in this package
#  ( and also the full pacakge , source etc... 
#    to be compiled for other plateforms )
#
export NCARG_ROOT=${NCARG_ROOT:-$SRC_MESONH/pub/ncl_ncarg-5.2.1.Linux_x86_64}
export PATH=$PATH:$NCARG_ROOT/bin
# WARNING : NCARG Man not installed in that version
export MANPATH=$MANPATH:$NCARG_ROOT/man  
#
# VARTTY : for graphic tty console identification
#
export VARTTY=`tty`
#
# Variable depending on $ARCH 
#
[ -f ${SRC_MESONH}/conf/conf_${ARCH} ] && . ${SRC_MESONH}/conf/conf_${ARCH}

#
# Optional Environnement variable/Module  Env
#
 
