#!/bin/sh
#SBATCH -J ibmCYL_2
#SBATCH -N 5            # nodes number
#SBATCH -n 480            # CPUs number (on all nodes) 
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 05:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

ln -sf ../001_prep_ideal_case/INIFILE* .
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

rm -f MNHOU*

export MPIRUN="Mpirun -np 480"

set -x
set -e

time ${MPIRUN} MESONH${XYZ}
#mv MNHOU.1.SEGM.010.nc CYL_100ks.nc

cd ../003_python
sbatch run_python
