#!/bin/sh
#SBATCH -J elec_old
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 8            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run_armles.eo%j   #
#SBATCH -e run_armles.eo%j   #
#SBATCH -t 02:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname
ln -sf ../../001_prep_ideal_case/KW78* .

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2
export MPIRUN="Mpirun -np 8"

time ${MPIRUN} MESONH${XYZ}

