#!/bin/sh
#SBATCH -J prep_arp2
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 4            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_arp2.eo%j   #
#SBATCH -e prep_arp2.eo%j   #
#SBATCH -t 00:15:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 
ln -sf ../PGD/PGD_FR* .
ln -sf ~/SAVE/GRIB_KTEST/arpifs.AN.20180513.00 .
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 4"

set -x
set -e
time ${MPIRUN} PREP_REAL_CASE${XYZ}
sbatch run_python
