#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x

ln -sf ../002_mesonh/ARM__.1.CEN4T.000.* .

rm -f visu_ARM.*.png

ncl  plot_arm.ncl
${POSTRUN} display visu_ARM.000001.png
${POSTRUN} display visu_ARM.000002.png
${POSTRUN} display visu_ARM.000003.png
${POSTRUN} display visu_ARM.000004.png
${POSTRUN} display visu_ARM.000005.png
${POSTRUN} display visu_ARM.000006.png
${POSTRUN} display visu_ARM.000007.png
${POSTRUN} display visu_ARM.000008.png
${POSTRUN} display visu_ARM.000009.png
${POSTRUN} display visu_ARM.000010.png
${POSTRUN} display visu_ARM.000011.png
${POSTRUN} display visu_ARM.000012.png
${POSTRUN} display visu_ARM.000013.png
${POSTRUN} display visu_ARM.000014.png
${POSTRUN} display visu_ARM.000015.png
${POSTRUN} display visu_ARM.000016.png
${POSTRUN} display visu_ARM.000017.png
${POSTRUN} display visu_ARM.000018.png
${POSTRUN} display visu_ARM.000019.png
${POSTRUN} display visu_ARM.000020.png
${POSTRUN} display visu_ARM.000021.png
${POSTRUN} display visu_ARM.000022.png
${POSTRUN} display visu_ARM.000023.png
${POSTRUN} display visu_ARM.000024.png
exit 0
