#!/bin/sh
#SBATCH -J diag_fanny
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 128            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o diag_fanny.eo%j   #
#SBATCH -e diag_fanny.eo%j   #
#SBATCH -t 00:10:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 128"

set -x
set -e


ls -lrt

time ${MPIRUN} DIAG${XYZ}
