#!/bin/sh
#SBATCH -J run_supercell
#SBATCH -N 20            # nodes number (=NBP)
#SBATCH -n 2560            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 12:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
#set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-SUPERCELL

export MPIRUN="Mpirun -np 2560"
ln -sf ../01_prep_ideal/SCELWK500m.* .

time ${MPIRUN} MESONH${XYZ} 

rm -f file_for_xtransfer pipe_name PRESSURE REMAP*
