#!/bin/sh
#SBATCH -J RECYL_5
#SBATCH -N 5            # nodes number
#SBATCH -n 480            # CPUs number (on all nodes) 
#SBATCH -o ideal.eo%j   #
#SBATCH -e ideal.eo%j   #
#SBATCH -t 18:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

ln -sf ../002_mesonh/RE1.* .
ln -sf ../002_mesonh/MUSTFATHER_PGD.* .
ln -sf ../004_prep_real_D2/RE1.spa00.* .
ln -sf ../004_prep_real_D2/RE2.* .
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-IBM

export MPIRUN="Mpirun -np 480"

set -x
set -e

time ${MPIRUN} MESONH${XYZ}

