#!/bin/sh
#SBATCH -J prep_kmap
#SBATCH -N 2            # nodes number (=NBP)
#SBATCH -n 20            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_kmap.eo%j   #
#SBATCH -e prep_kmap.eo%j   #
#SBATCH -t 04:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq//DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 20"
set -x
set -e

ln -sf $HOME/SAVE/GRIB_KTEST/ecmwf.OD.1999091* .

ls -lrt

rm -f CPL_19990917.12.???
cp PRE_REAL1.nam_1 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep1
 
ls -lrt


rm -f CPL_19990917.18.???
cp PRE_REAL1.nam_2 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep2

ls -lrt

rm -f CPL_19990918.00.???
cp PRE_REAL1.nam_3 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep3

ls -lrt

rm -f ecmwf*
rm -f PRE_REAL1.nam
rm -f file_for_xtransfer pipe_name
sbatch run_spa_real
ja
