#!/bin/sh
#SBATCH -J Blaze
#SBATCH -N 1            # nodes number
#SBATCH -n 4          # CPUs number (on all nodes)
#SBATCH -o zzout.eo%j   #
#SBATCH -e zzout.eo%j   #
#SBATCH -t 00:20:00    # time limit
#SBATCH -p normal256

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 4"

set -x
set -e

time ${MPIRUN} PREP_IDEAL_CASE${XYZ}

#CINIFILE=$(cat PRE_IDEA1.nam | grep 'CINIFILE=' | cut -d "'" -f 2)
#CINIFILEPGD=$(cat PRE_IDEA1.nam | grep 'CINIFILEPGD=' | cut -d "'" -f 2)

cd ../02_mesonh
sbatch run_mesonh
