#!/bin/sh
set -x
set -e
rm -f ICART* OUT*  EXSEG?.nam 

export CHIMIE_FILES=${CHIMIE_FILES:-"$HOME/CHIMIE_FILES"} 

ln -sf ${CHIMIE_FILES}/tuv50/DATAE1 .
ln -sf ${CHIMIE_FILES}/tuv50/DATAJ1 .
ln -sf ${CHIMIE_FILES}/tuv50/DATAS1 .
cp EXSEG1.nam.src EXSEG1.nam
ln -sf  ../002_arp2lfi/CPLCH20040810.18.*??? .
ln -sf ../001_pgd1/ICARTT1008_PGD_15km.??? .
time ${MPIRUN} MESONH${XYZ}
