#!/bin/sh
#SBATCH -J ibmMUS_3
#SBATCH -N 1            # nodes number
#SBATCH -n 1            # CPUs number (on all nodes) 
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 00:40:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2
ln -sf ../001_prep_ideal_case/MUSTFATHER_PGD* .
ln -sf ../002_mesonh/MUSTD1.* .
export MPIRUN="Mpirun -np 1"

set -x
set -e

time ${MPIRUN} SPAWNING${XYZ}

sed 's/MUSTD1/MUSTD1.spa00/' MUSTD1.spa00.des > MUSTD1.spa00.des2
mv -f MUSTD1.spa00.des2 MUSTD1.spa00.des

sed "s/CINIFILEPGD     = \" /CINIFILEPGD     = \"MUSTD1.spa00/" MUSTD1.spa00.des > temp
mv -f temp MUSTD1.spa00.des

cd ../004_prep_real_D2_IBM
sbatch run_prep
