#!/bin/sh
#SBATCH -J run1_fanny
#SBATCH -N 10            # nodes number
#SBATCH -n 320            # CPUs number (on all nodes) 
#SBATCH -o run1_fanny.eo%j   #
#SBATCH -e run1_fanny.eo%j   #
#SBATCH -t 01:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
#set -e
# Nom de la machine
hostname 

. ~rodierq//DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2
export MPIRUN="Mpirun -np 320"

#set -x
#set -e


ln -sf ../LIMA/PGD* .
ln -sf ../LIMA/A_2008090* .
time ${MPIRUN} MESONH${XYZ}
