!     ######spl
 MODULE MODI_SET_SURFEX_FILE_NAME_MNH
!####################
INTERFACE
!
SUBROUTINE SET_SURFEX_FILE_NAME_MNH(HMASK)
  CHARACTER(LEN=4),  INTENT(IN)  :: HMASK
END SUBROUTINE SET_SURFEX_FILE_NAME_MNH
!
END INTERFACE
!
END MODULE MODI_SET_SURFEX_FILE_NAME_MNH
    

!     ######spl
      SUBROUTINE  SET_SURFEX_FILE_NAME_MNH(HMASK)
!     ###############################  
!
USE MODD_LUNIT_n,      ONLY : CMASK_SURFEX
IMPLICIT NONE
!
CHARACTER(LEN=4),  INTENT(IN)  :: HMASK

CMASK_SURFEX=HMASK      
!     ######spl
END SUBROUTINE  SET_SURFEX_FILE_NAME_MNH
!     ###############################        
