#!/bin/sh
#SBATCH -J azf_prep
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_azf.eo%j   #
#SBATCH -e prep_azf.eo%j   #
#SBATCH -t 01:30:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

ln -sf ../003_nest/PGD_AZF* .
ln -sf $HOME/SAVE/GRIB_KTEST/ecmwf.OD.20010921.00.09
ln -sf $HOME/SAVE/GRIB_KTEST/ecmwf.OD.20010921.00.12
rm -f  OUTPUT_LISTING* pipe* *.tex

export MPIRUN="Mpirun -np 1"

set -x
set -e

cp -f PRE_REAL1.nam_09 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0 OUTPUT_LISTING0_09
cp -f PRE_REAL1.nam_12 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0 OUTPUT_LISTING0_12

rm -f PRE_REAL1.nam
cd ../005_spa_mod1_mod2/
sbatch run_spawning_xyz
