#!/bin/sh
#SBATCH -J run3_dust
#SBATCH -N 1            # nodes number
#SBATCH -n 16            # CPUs number (on all nodes) 
#SBATCH -o run3_dust.eo%j   #
#SBATCH -e run3_dust.eo%j   #
#SBATCH -t 10:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 16"

set -x
set -e


ls -lrt

rm -f DUST7.1.W5_S3.*
cp EXSEG1.nam.3 EXSEG1.nam
time ${MPIRUN} MESONH${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_run3
mv OUTPUT_LISTING1  OUTPUT_LISTING1_run3

ls -lrt

rm -f file_for_xtransfer pipe_name PRESSURE REMAP*
rm -f EXSEG1.nam

ja
