#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x

ln -sf ../002_mesonh/EXPER.1.HYD2D.002.nc .
ln -sf ../002_mesonh/EXPER.1.HYD2D.003.nc .

rm -f visu_2Drelief.*.png

ncl  plot_2Drelief.ncl
${POSTRUN} display visu_2Drelief.000001.png
${POSTRUN} display visu_2Drelief.000002.png
${POSTRUN} display visu_2Drelief.000003.png
${POSTRUN} display visu_2Drelief.000004.png
${POSTRUN} display visu_2Drelief.000005.png
${POSTRUN} display visu_2Drelief.000006.png
${POSTRUN} display visu_2Drelief.000007.png
${POSTRUN} display visu_2Drelief.000008.png
${POSTRUN} display visu_2Drelief.000009.png
${POSTRUN} display visu_2Drelief.000010.png
${POSTRUN} display visu_2Drelief.000011.png
${POSTRUN} display visu_2Drelief.000012.png
${POSTRUN} display visu_2Drelief.000013.png
${POSTRUN} display visu_2Drelief.000014.png
${POSTRUN} display visu_2Drelief.000015.png
${POSTRUN} display visu_2Drelief.000016.png
exit 0
