#!/bin/sh
#SBATCH -J GABLS1
#SBATCH -N 4           # nodes number
#SBATCH -n 256         # CPUs number (on all nodes) 
#SBATCH -o G1_.eo%j   #
#SBATCH -e G1_.eo%j   #
#SBATCH -t 08:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-GABLS1

export MPIRUN="Mpirun -np 256 "

set -x
set -e

time ${MPIRUN} MESONH${XYZ}
./run_select_var_from_nc
~                               
