#!/bin/sh
#SBATCH -J elecKW78
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run_armles.eo%j   #
#SBATCH -e run_armles.eo%j   #
#SBATCH -t 00:10:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 1"

time ${MPIRUN} PREP_IDEAL_CASE${XYZ}
cd ../002_mesonh/old
sbatch run_mesonh_xyz
cd ../ice3
sbatch run_mesonh_xyz
cd ../lima
sbatch run_mesonh_xyz
cd ../lima2
sbatch run_mesonh_xyz
