all: E001_pgd1 E002_pgd2 E003_pgd3 E004_pgd4 E005_nest E006_preal1 E007_spawn E008_preal2 E009_spawn E010_preal3 E011_spawn E012_preal4 E013_run


E001_pgd1 :
	cd 001_pgd1	       && run_prep_pgd_xyz 
E002_pgd2:
	cd 002_pgd2	       && run_prep_pgd_xyz
E003_pgd3:
	cd 003_pgd3	       && run_prep_pgd_xyz
E004_pgd4:
	cd 004_pgd4	       && run_prep_pgd_xyz
E005_nest:
	cd 005_nest            && run_prep_nest_pgd_xyz
E006_preal1 :
	cd 006_preal1	       && run_arp2lfi_xyz
E007_spawn:
	cd 007_spa_mod1_mod2   && run_spawning_xyz
E008_preal2:
	cd 008_preal2	       && run_preal_xyz
E009_spawn:
	cd 009_spa_mod2_mod3   && run_spawning_xyz
E010_preal3:
	cd 010_preal3	       && run_preal_xyz
E011_spawn:
	cd 011_spa_mod3_mod4   && run_spawning_xyz
E012_preal4:
	cd 012_preal4          && run_preal_xyz
E013_run:
	cd 013_run             && run_mesonh_xyz
