#!/bin/sh
#SBATCH -J ideal_cyc
#SBATCH -N 2            # nodes number (=NBP)
#SBATCH -n 40            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal_cyc.eo%j   #
#SBATCH -e ideal_cyc.eo%j   #
#SBATCH -t 01:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 40"

set -x
set -e


ls -lrt

rm -f CL.REF04.D70.E_00.???
cp PRE_IDEA1.nam_04km_00 PRE_IDEA1.nam
time ${MPIRUN} PREP_IDEAL_CASE${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_ideal1
 
ls -lrt 

rm -f CL.REF04.D70.E_48.???
cp PRE_IDEA1.nam_04km_48 PRE_IDEA1.nam
time ${MPIRUN} PREP_IDEAL_CASE${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_ideal2

rm -f PRE_IDEA1.nam
rm -f file_for_xtransfer pipe_name

ls -lrt 

sbatch run_prep_real_case

ja
