#!/bin/sh
#SBATCH -J pgd_cyc
#SBATCH -N 1            # nodes number
#SBATCH -n 4            # CPUs number (on all nodes) 
#SBATCH -o pgd_cyc.eo%j   #
#SBATCH -e pgd_cyc.eo%j   #
#SBATCH -t 02:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 4 "

set -x
set -e

ln -sf $MESONH/PGD/ecoclimats_v2.* .
ln -sf $MESONH/PGD/gtopo30.* .
ln -sf $MESONH/PGD/clay_fao.* .
ln -sf $MESONH/PGD/sand_fao.* .



rm -f PGD_mer04km.???
time ${MPIRUN} PREP_PGD${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_pgd
touch PGD_mer04km.des

ls -lrt
rm -f *.dir *.hdr
rm -f file_for_xtransfer pipe_name

sbatch run_prep_ideal
ja
