#!/bin/sh
#SBATCH -J ibmMUS_2
#SBATCH -N 15            # nodes number
#SBATCH -n 1600            # CPUs number (on all nodes) 
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 03:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

ln -sf ../001_prep_ideal_case/MUSTFATHER* .
export MPIRUN="Mpirun -np 1600"

set -x
set -e

time ${MPIRUN} MESONH${XYZ}

ln -sf MNHOU.1.SEGM.004.nc MUSTD1.nc
ln -sf MNHOU.1.SEGM.004.des MUSTD1.des

cd ../003_spawn_D2
sbatch run_spawning
