#!/bin/sh
#SBATCH -J azf
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 16            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 02:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

ln -sf ../006_preal/PGD* .
ln -sf ../006_preal/CPL* .
ln -sf ../004_arp2lfi/CPL* .
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 8"

set -x
set -e
ls -lrt

time ${MPIRUN} MESONH${XYZ}
cd ../009_python
sbatch run_python
