#!/bin/sh
#SBATCH -J azf_prep
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 8            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o prep_azf.eo%j   #
#SBATCH -e prep_azf.eo%j   #
#SBATCH -t 01:30:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

ln -sf ../003_nest/PGD_AZF* .
ln -sf ../004_arp2lfi/CPL_J1_20010921.09.* .
ln -sf ../004_arp2lfi/CPL_J3_20010921.09.* .
ln -sf ../005_spa_mod1_mod2/CPL_J1_20010921.09.spa2.* .
ln -sf ../005_spa_mod1_mod2/CPL_J3_20010921.09.spa2.* .

export MPIRUN="Mpirun -np 8"

time ${MPIRUN} PREP_REAL_CASE${XYZ}
cd ../007_run
sbatch run_mesonh
