#!/bin/sh
#SBATCH -J ideal_sterao
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 16            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal_sterao.eo%j   #
#SBATCH -e ideal_sterao.eo%j   #
#SBATCH -t 01:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-DEBUG-STERAO
export MPIRUN="Mpirun -np 16"

set -x
set -e

rm -f STERAO_LARGE.* STERAO_PGD.*
time ${MPIRUN} PREP_IDEAL_CASE${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_ideal
 
rm -f file_for_xtransfer pipe_name

sbatch run_mesonh
ja
