MODULE MODD_PARAM
  IMPLICIT NONE 

  CHARACTER(LEN=*), PARAMETER :: VERSION_ID='lfi2cdf Ver. Alpha'
  INTEGER, PARAMETER :: INT   = 1
  INTEGER, PARAMETER :: FLOAT = 2
  INTEGER, PARAMETER :: TEXT  = 3
  INTEGER, PARAMETER :: BOOL  = 4

  INTEGER, PARAMETER :: D0 = 100
  INTEGER, PARAMETER :: D1 = 200
  INTEGER, PARAMETER :: D2 = 300
  INTEGER, PARAMETER :: D3 = 400

  INTEGER, PARAMETER :: NOTFOUND = -1

  INTEGER, PARAMETER :: FM_FIELD_SIZE = 32
  
END MODULE MODD_PARAM
