MODULE MODD_PARAM
  USE MODE_FIELD, ONLY: TYPEUNDEF, TYPEINT, TYPELOG, TYPEREAL, TYPECHAR, TYPEDATE

  IMPLICIT NONE 

  CHARACTER(LEN=*), PARAMETER :: VERSION_ID='lfi2cdf Ver. Alpha'

  INTEGER, PARAMETER :: D0 = 100
  INTEGER, PARAMETER :: D1 = 200
  INTEGER, PARAMETER :: D2 = 300
  INTEGER, PARAMETER :: D3 = 400

  INTEGER, PARAMETER :: NOTFOUND = -1

  INTEGER, PARAMETER :: FM_FIELD_SIZE = 32
  
END MODULE MODD_PARAM
