#!/bin/sh
#SBATCH -J sparea_charmex
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o sparea_charmex.eo%j   #
#SBATCH -e sparea_charmex.eo%j   #
#SBATCH -t 02:30:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-RELACS


export MPIRUN="Mpirun -np 1"

set -x
set -e


ls -lrt

rm -f CHARM.1.SEG01.00?.spa04.*
rm -f CPLCH2_3006_0*

cp SPAWN1.nam_1 SPAWN1.nam
time ${MPIRUN} SPAWNING${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_spa1
mv OUTPUT_LISTING2  OUTPUT_LISTING2_spa1
mv OUTPUT_LISTING0  OUTPUT_LISTING0_spa1
ls -lrt
cp PRE_REAL1.nam_dom2_1 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep_dom2_1
mv OUTPUT_LISTING1  OUTPUT_LISTING1_prep_dom2_1
ls -lrt


cp SPAWN1.nam_2 SPAWN1.nam
time ${MPIRUN} SPAWNING${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_spa2
mv OUTPUT_LISTING2  OUTPUT_LISTING2_spa2
mv OUTPUT_LISTING0  OUTPUT_LISTING0_spa2
ls -lrt
cp PRE_REAL1.nam_dom2_2 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep_dom2_2
mv OUTPUT_LISTING1  OUTPUT_LISTING1_prep_dom2_2

cp SPAWN1.nam_3 SPAWN1.nam
time ${MPIRUN} SPAWNING${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_spa3
mv OUTPUT_LISTING2  OUTPUT_LISTING2_spa3
mv OUTPUT_LISTING0  OUTPUT_LISTING0_spa3
ls -lrt
cp PRE_REAL1.nam_dom2_3 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep_dom2_3
mv OUTPUT_LISTING1  OUTPUT_LISTING1_prep_dom2_3

cp SPAWN1.nam_4 SPAWN1.nam
time ${MPIRUN} SPAWNING${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_spa4
mv OUTPUT_LISTING2  OUTPUT_LISTING2_spa4
mv OUTPUT_LISTING0  OUTPUT_LISTING0_spa4
ls -lrt
cp PRE_REAL1.nam_dom2_4 PRE_REAL1.nam
time ${MPIRUN} PREP_REAL_CASE${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_prep_dom2_4
mv OUTPUT_LISTING1  OUTPUT_LISTING1_prep_dom2_4

ls -lrt
rm -f PRE_REAL1.nam SPAWN1.nam
rm -f file_for_xtransfer pipe_name
sbatch run_mesonh2

ja
