#!/bin/sh
#SBATCH -J pgd_charmex
#SBATCH -N 1            # nodes number
#SBATCH -n 1            # CPUs number (on all nodes) 
#SBATCH -o pgd_charmex.eo%j   #
#SBATCH -e pgd_charmex.eo%j   #
#SBATCH -t 00:20:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2-RELACS

export MPIRUN="Mpirun -np 1"

set -x
set -e

ln -sf $MESONH/PGD/ECOCLIMAP_II_EUROP_V2.0.* .
ln -sf $MESONH/PGD/gtopo30.* .
ln -sf $MESONH/PGD/CLAY_HWSD_MOY.* .
ln -sf $MESONH/PGD/SAND_HWSD_MOY.* .
ln -sf $HOME/SAVE/GRIB_KTEST/CHARMEX/DATA_EMIS/*.asc .
ls -lrt

rm -f CHARMEX0714_PGD_50km.???
cp PRE_PGD1.nam_1 PRE_PGD1.nam
time ${MPIRUN} PREP_PGD${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_pgd1
touch CHARMEX0714_PGD_50km.des

ls -lrt


rm -f CHARMEX0714_PGD_12km5.???
cp PRE_PGD1.nam_2 PRE_PGD1.nam
time ${MPIRUN} PREP_PGD${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_pgd2
touch CHARMEX0714_PGD_12km5.des

ls -lrt


rm -f *.neste1.*
time ${MPIRUN} PREP_NEST_PGD${XYZ}
mv OUTPUT_LISTING0  OUTPUT_LISTING0_nest
touch CHARMEX0714_PGD_50km.neste1.des
touch CHARMEX0714_PGD_12km5.neste1.des

ls -lrt
rm -f *.dir *.hdr
rm -f PRE_PGD1.nam
rm -f file_for_xtransfer pipe_name
rm -f *.asc


sbatch run_prep_real_case

ja

