#!/bin/sh
#SBATCH -J ibmMUS_5
#SBATCH -N 15            # nodes number
#SBATCH -n 1600            # CPUs number (on all nodes) 
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 23:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 1600"

set -x
set -e

cp -f EXSEG1.nam_seg1 EXSEG1.nam
cp -f EXSEG2.nam_seg1 EXSEG2.nam

time ${MPIRUN} MESONH${XYZ}

# Run en entier :
# sbatch run_mesonh2

#Run simple
#cd ../006_python
#sbatch run_python

