#!/bin/sh
#SBATCH -J ideal
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 32            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal.eo%j   #
#SBATCH -e ideal.eo%j   #
#SBATCH -t 00:10:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 


. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 32"

set -x
set -e

time ${MPIRUN} PREP_IDEAL_CASE${XYZ}
mv OUTPUT_LISTING1  OUTPUT_LISTING1_ideal
 
sbatch run_mesonh
ja
