#!/bin/sh
#SBATCH -J ibmMUS_4
#SBATCH -N 1            # nodes number
#SBATCH -n 40            # CPUs number (on all nodes) 
#SBATCH -o run.eo%j   #
#SBATCH -e run.eo%j   #
#SBATCH -t 01:00:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname 

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2
ln -sf ../003_spawn_D2/MUSTD1.spa* .
export MPIRUN="Mpirun -np 40"

set -x
set -e

time ${MPIRUN} PREP_REAL_CASE${XYZ}

cd ../005_MNHD2
sbatch run_mesonh
