#!/bin/bash
#SBATCH -J ALM3_02
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 1            # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o ideal_fire.eo%j   #
#SBATCH -e ideal_fire.eo%j   #
#SBATCH -t 00:10:00    # time limit

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
set -e
# Nom de la machine
hostname

. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 1"

set -x
set -e

ln -sf ../01_PREP/FIRE* .

time ${MPIRUN} SPAWNING${XYZ}

sed -i 's/FIRE_INI/FIRE_INI.spa00/g' FIRE_INI.spa00.des
sed -i 's/CINIFILEPGD     = "/CINIFILEPGD     ="FIRE_INI.spa00/g' FIRE_INI.spa00.des

rm -f file_for_xtransfer pipe_name

cd ../03_RUN_PRE/
sbatch run_mesonh
