#!/bin/bash
#MNH_LIC Copyright 1994-2019 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.

set -x
# On va lancer la compilation dans le répertoire de lancement du job
pwd

# Chargement du profil (qui contient le source vers l'env ifpen-mesonh)
. ../conf/profile_mesonh-LXgfortran-R8I4-MNH-V5-6-0-MPIAUTO-O2

time gmake -j 10
time gmake -j 1 installmaster

~                       

