#!/bin/bash
#SBATCH --verbose
#SBATCH --job-name=compile
#SBATCH --time=02:05:00
#SBATCH --mem=9600
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --share
#SBATCH -o MasterI.eo%j   #
#SBATCH -e MasterI.eo%j   #
#SBATCH --export=NONE

export VER_USER=                ########## Your own USER Directory
set -x

# On va lancer la compilation dans le répertoire de lancement du job
. ../conf/profile_mesonh-LXifortI4-MNH-V4-10-1-${VER_USER}-MPIINTEL-O3

time gmake user
time gmake -j 1 installuser
