#!/bin/bash
#MNH_LIC Copyright 1994-2019 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
#SBATCH --verbose
#SBATCH --job-name=compile
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH -o MasterI_belenos.eo%j   #
#SBATCH -e MasterI_belenos.eo%j   #

set -x
# On va lancer la compilation dans le répertoire de lancement du job
pwd

. ../conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-MPIAUTO-O3

time make -j 16
time make -j 1 installmaster

