#!/bin/bash
#SBATCH -J Examples
#SBATCH -N 1            # nodes number
#SBATCH -n 4            # CPUs number (on all nodes) 
#SBATCH -C GENOA
##SBATCH --exclusive           
#SBATCH -o Examples.eo%j   #
#SBATCH -e Examples.eo%j   #
#SBATCH -t 01:00:00    # time limit
#SBATCH --export=NONE
#SBATCH -A mnh # put here you account/projet name

# Echo of commands
ulimit -c 0
ulimit -s unlimited
# Stop job at first error
#set -e
set -x
# Machine name
hostname 

unset MAKEFLAGS

. ../conf/profile_mesonh-LXcray-R8I4-MNH-V5-6-2-MPICRAY-O2
export MONORUN="Exec srun -l -n 1 --export=ALL"
export MPIRUN="Exec srun -l -n 4 --export=ALL"
export POSTRUN="echo "

cd $SRC_MESONH/MY_RUN/KTEST/003_KW78 
make -k
#
echo "#################################################################################"
echo "##NEXT CASE######################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/001_2Drelief 
make -k
#
echo "#################################################################################"
echo "##NEXT CASE######################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/002_3Drelief 
make -k
#
echo "#################################################################################"
echo "##NEXT CASE######################################################################"
echo "#################################################################################"

cd $SRC_MESONH/MY_RUN/KTEST/004_Reunion
make -k << EOF 


EOF
#
echo "#################################################################################"
echo "##NEXT CASE######################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/007_16janvier
make -k << EOF 


EOF
#
echo "#################################################################################"
echo "##NEXT CASE######################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/014_LIMA 
make -k

