#!/bin/bash
#MNH_LIC Copyright 1994-2019 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
#SBATCH --job-name=compile_MNH
#SBATCH -N 1 -n 1 -c 16
#SBATCH -o Sortie_compile_MasterI.eo%j      
#SBATCH --export=NONE
#SBATCH -p compil
#SBATCH -A mnh@cpu # put here your account/projet name

set -x
# On va lancer la compilation dans le répertoire de lancement du job
pwd

. ../conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-MPIINTEL-O2

time gmake -j 16
time gmake -j 1 installmaster

