#!/bin/bash
#SBATCH -J Examples
#SBATCH -N 2            # nodes number
#SBATCH -n 4            # CPUs number (on all nodes) 
#SBATCH -q qos_cpu-dev
#SBATCH --exclusive           
#SBATCH -o Examples.eo%j   #
#SBATCH -e Examples.eo%j   #
#SBATCH -t 01:00:00    # time limit
#SBATCH --export=NONE
#SBATCH -A mnh@cpu # put here you account/projet name

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
#set -e
set -x
# Nom de la machine
hostname 

unset MAKEFLAGS

. ../conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-MPIINTEL-O2
export MONORUN="Exec srun -l -n 1 --export=ALL numabind_core_slurm"
export MPIRUN="Exec srun -l -n 4 --export=ALL numabind_core_slurm"
export POSTRUN="echo "

cd $SRC_MESONH/MY_RUN/KTEST/003_KW78 
make -k
#
echo "#################################################################################"
echo "##CAS SUIVANT####################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/001_2Drelief 
make -k
#
echo "#################################################################################"
echo "##CAS SUIVANT####################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/002_3Drelief 
make -k
#
echo "#################################################################################"
echo "##CAS SUIVANT####################################################################"
echo "#################################################################################"

cd $SRC_MESONH/MY_RUN/KTEST/004_Reunion
make -k << EOF 


EOF
#
echo "#################################################################################"
echo "##CAS SUIVANT####################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/007_16janvier
make -k << EOF 


EOF
#
echo "#################################################################################"
echo "##CAS SUIVANT####################################################################"
echo "#################################################################################"
cd $SRC_MESONH/MY_RUN/KTEST/014_LIMA 
make -k

