#!/bin/bash
#MNH_LIC Copyright 1994-2019 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
#SBATCH --verbose
#SBATCH --job-name=compile
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH -o VuserII_belenos.eo%j   #
#SBATCH -e VUserII_belenos.eo%j   #

export VER_USER=                     ######## Your own USER Directory

set -x
# On va lancer la compilation dans le répertoire de lancement du job
pwd

. ../conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-${VER_USER}-MPIAUTO-O3

time make user -j 2
time make -j 1 installuser
