#!/bin/bash
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
ln -sf ${SRC_MESONH}/src/LIB/Python/* .
ln -sf ../002_mesonh/REL3D.1.EXP01.002.nc .

python3 plot_002_3DRelief.py
${POSTRUN} display tempgraph1.png
#${POSTRUN} convert *.png 002_3DRelief.pdf
#${POSTRUN} evince 002_3DRelief.pdf
