#!/bin/sh
#SBATCH -J salt_run
#SBATCH -N 1            # nodes number (=NBP)
#SBATCH -n 32           # CPUs number (on all nodes) (=NBP*TPN)
#SBATCH -o run1_16jan.eo%j   #
#SBATCH -e run1_16jan.eo%j   #
#SBATCH -t 04:00:00    # time limit
#
## Echo des commandes
ulimit -c 0
ulimit -s unlimited
## Arrete du job des la premiere erreur
set -e
## Nom de la machine
#hostname
#
. ~rodierq/DEV_57/MNH-PHYEX070-b95d84d7/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-ECRAD140-MPIAUTO-O2

export MPIRUN="Mpirun -np 32"

set -x
set -e

ln -sf ../003_prep_real/18JAN* .
ln -sf ../002_prep_nest/Arome* .

rm -f OUTPUT_LISTING_*
rm -f SALHS*

cp -f EXSEG1.nam_1 EXSEG1.nam
cp -f EXSEG2.nam_1 EXSEG2.nam

time ${MPIRUN} MESONH${XYZ}
mv -f OUTPUT_LISTING1 OUTPUT_LISTING1_1

cp -f EXSEG1.nam_2 EXSEG1.nam
cp -f EXSEG2.nam_2 EXSEG2.nam

time ${MPIRUN} MESONH${XYZ}
mv -f OUTPUT_LISTING1 OUTPUT_LISTING1_2

cp -f EXSEG1.nam_3 EXSEG1.nam
cp -f EXSEG2.nam_3 EXSEG2.nam

time ${MPIRUN} MESONH${XYZ}
mv -f OUTPUT_LISTING1 OUTPUT_LISTING1_3

cd ../005_diag
sbatch run_diag
